using System;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using VortexArena.Core;
using VortexArena.Core.UI;
using VortexArena.Net;
using VortexArena.Protocol;

namespace VortexArena.App.Admin
{
    /// <summary>
    /// Stats panel (opened by the chip between the scores or the <c>I</c> key).
    /// <para><b>Why row based:</b> the panel is not a read-only table but the screen where the
    /// operator does <i>record keeping</i> (fixing names, body measurement, calibration reload).
    /// Each player is a row (<see cref="AdminStatsRow"/>): alignment comes from the column grid,
    /// actions sit on the row and the list scrolls — <b>no cap</b>, everyone is drawn.</para>
    /// <para><b>ONE table for every player.</b> In a team mode a group row per team breaks it up
    /// (<see cref="RefreshRows"/>); a team-less mode draws the same table ranked by score, with no
    /// group rows. ⚠️ No two-column split any more: two half-width copies of the row meant two
    /// column grids that drifted apart, and the narrow copy could not carry the row's cells.</para>
    /// <para>⚠️ <b>Team-less players stay visible</b> in a team mode — see
    /// <see cref="BuildRedSection"/>; they are the whole roster during Lobby.</para>
    /// <para><b>No invented metrics:</b> only data actually on the wire (K/D/score from §5.3
    /// <c>lobby_state</c>; battery/controllers from <c>status</c>; ping = client-measured RTT,
    /// §6.7 <c>net_stats</c>). ⚠️ <b>Damage and accuracy are not in the protocol, so not here
    /// either.</b> Jitter and packet loss are measured but not shown: ping is the only number the
    /// operator can act on.</para>
    /// <para>⚠️ <b>HP is deliberately absent from the row</b> — reasoning in the
    /// <see cref="AdminStatsRow"/> class doc; do not "restore" it.</para>
    /// <para>⚠️ <b>There is no BULK reset button.</b> Resetting alignment is a per-player decision
    /// made on the row (SIFIRLA, tap/hold); the footer only carries the three harmless bulk jobs
    /// (body tracking restart, measure everyone, reload everyone's calibration).</para>
    /// <para><b>Look comes from the prefab</b>
    /// (<c>_Shared/App/Resources/UI/AdminStatsPanel.prefab</c>, generated by
    /// <c>GirdapUiBuilder</c>); this class only writes data and places rows.</para>
    /// </summary>
    public class AdminStatsPanel : MonoBehaviour
    {
        private const float RefreshInterval = 0.5f;

        /// <summary>Auto-close time of the toast (s), so a forgotten one does not sit on the list
        /// forever.</summary>
        private const float PopupSeconds = 6f;

        /// <summary>CSS <c>.tgroup</c> height — the team header inside the table.</summary>
        private const float GroupHeight = 36f;

        /// <summary>CSS <c>.info</c> gap between two label+value pairs.</summary>
        private const float InfoGap = 24f;

        /// <summary>CSS <c>.toast</c> metrics: side padding, icon box and icon gap.</summary>
        private const float ToastPadding = 14f;

        /// <inheritdoc cref="ToastPadding"/>
        private const float ToastIcon = 20f;

        /// <inheritdoc cref="ToastPadding"/>
        private const float ToastGap = 8f;

        // Info strip slots. ⚠️ The ORDER is a contract with the prefab builder (GirdapUiBuilder
        // writes the same labels in the same order); an index moved here silently relabels a value.
        private const int InfoPhase = 0;
        private const int InfoRemaining = 1;
        private const int InfoMode = 2;
        private const int InfoMap = 3;
        private const int InfoDuration = 4;
        private const int InfoScoreLimit = 5;
        private const int InfoServer = 6;
        private const int InfoSnapshot = 7;
        private const int InfoAdmins = 8;
        private const int InfoCustomers = 9;

        /// <summary>FFA sort buffer (avoids a list allocation per refresh).</summary>
        private readonly List<AdminPlayerView> _sorted = new List<AdminPlayerView>();

        /// <summary>Row pool: instances are hidden, never destroyed (same pattern as
        /// <see cref="AdminHud"/>) — Instantiate/Destroy per refresh causes GC and layout
        /// jitter.</summary>
        private readonly List<AdminStatsRow> _rows = new List<AdminStatsRow>();

        /// <summary>Rows bound in the last refresh. <see cref="Tick"/>, the bulk actions and the
        /// calibration result walk THIS, not the pool: the tail of the pool is hidden.</summary>
        private readonly List<AdminStatsRow> _live = new List<AdminStatsRow>();

        /// <summary>Red section buffer: red team + the team-less. See <see cref="BuildRedSection"/>.</summary>
        private readonly List<AdminPlayerView> _redSection = new List<AdminPlayerView>();

        // ⚠️ All fields are [SerializeField] — the look comes from the PREFAB, this class only
        // writes data.

        [Tooltip("Açılıp kapanan kart — panel kapalıyken bu obje devre dışı bırakılır.")]
        [SerializeField] private GameObject _root;
        [Tooltip("KAPAT düğmesi — tur sonu beklerken TURA DEVAM'a döner.")]
        [SerializeField] private UiButtonStyle _closeButton;

        [Header("Başlık")]
        [Tooltip("Takımlı kipin mini skor şeridi; takımsız kipte gizlenir.")]
        [SerializeField] private GameObject _scorebugRoot;
        [SerializeField] private TextMeshProUGUI _scoreRedText;
        [SerializeField] private TextMeshProUGUI _scoreBlueText;
        [Tooltip("Takımsız kipin tek satır başlığı (LİDER · EKİP TOPLAMI); takımlı kipte gizlenir.")]
        [SerializeField] private TextMeshProUGUI _headline;

        [Header("Bilgi şeridi")]
        [Tooltip("Etiket+değer çiftlerinin kökleri — sırası koddaki Info* sabitleriyle aynıdır.")]
        [SerializeField] private RectTransform[] _infoItems;
        [Tooltip("Yukarıdaki çiftlerin değer yazıları; genişlikleri koddan ölçülür.")]
        [SerializeField] private TextMeshProUGUI[] _infoValues;

        [Header("Oyuncu listesi")]
        [SerializeField] private AdminStatsRow _rowPrefab;
        [Tooltip("ScrollRect'in content'i — satırlar buranın altındadır, yüksekliği koddan sürülür.")]
        [SerializeField] private RectTransform _rowContainer;
        [SerializeField] private ScrollRect _scroll;
        [SerializeField] private float _rowGap = 4f;
        [Tooltip("Başlık şeridindeki K · D · K/D hücreleri. Silah ve rakip olmayan modlarda " +
                 "gizlenir; bağlanmazsa satır hücreleri yine de gizlenir.")]
        [SerializeField] private GameObject[] _killDeathHeaderCells;

        [Header("Takım grup satırları")]
        [SerializeField] private RectTransform _redGroup;
        [Tooltip("Sol taraftaki takım adı — takımsız oyuncu varsa sayısını da yazar.")]
        [SerializeField] private TextMeshProUGUI _redGroupName;
        [SerializeField] private TextMeshProUGUI _redGroupMeta;
        [SerializeField] private TextMeshProUGUI _redGroupKills;
        [SerializeField] private TextMeshProUGUI _redGroupDeaths;
        [SerializeField] private TextMeshProUGUI _redGroupScore;
        [SerializeField] private RectTransform _blueGroup;
        [SerializeField] private TextMeshProUGUI _blueGroupName;
        [SerializeField] private TextMeshProUGUI _blueGroupMeta;
        [SerializeField] private TextMeshProUGUI _blueGroupKills;
        [SerializeField] private TextMeshProUGUI _blueGroupDeaths;
        [SerializeField] private TextMeshProUGUI _blueGroupScore;

        [Header("Toplu eylemler")]
        [Tooltip("Tüm gözlüklerde gövde izlemesini yeniden başlatır (§6.11). Onay istemez: hiçbir " +
                 "veri kaybolmaz, bedeli herkeste birkaç saniyelik gövde donmasıdır — TÜMÜNÜ " +
                 "ÖLÇEKLENDİR ile aynı sınıf. Başlıklar bunu zaten kendiliğinden deniyor; bu " +
                 "düğme, otomatik denemelerin aralığı büyüdükten sonra hemen denetmek içindir.")]
        [SerializeField] private UiButtonStyle _restartBodyAllButton;
        [SerializeField] private UiButtonStyle _measureAllButton;
        [SerializeField] private UiButtonStyle _calibrateAllButton;
        [Tooltip("Alt şeridin sol tarafındaki açıklama — tur sonu beklerken çıkışı yazar.")]
        [SerializeField] private TextMeshProUGUI _footHint;

        [Header("Uyarı şeridi")]
        [SerializeField] private GameObject _popupRoot;
        [Tooltip("Şeridin kendisi — genişliği yazıya göre koddan ölçülür.")]
        [SerializeField] private RectTransform _popupShape;
        [SerializeField] private Image _popupIcon;
        [SerializeField] private TextMeshProUGUI _popupText;
        [Tooltip("Şeridin tamamını kaplayan kapatma düğmesi (şeritte ayrı bir X yok).")]
        [SerializeField] private Button _popupCloseButton;

        private float _nextRefresh;
        private bool _dirty = true;

        /// <summary>Row height read from the prefab (fallback <see cref="AdminStatsRow.Height"/>),
        /// so resizing a row reflows the list.</summary>
        private float _rowHeight = -1f;

        /// <summary>When the toast closes (<c>Time.unscaledTime</c>); &lt; 0 = closed.</summary>
        private float _popupUntil = -1f;

        /// <summary>Was the panel open on the previous refresh — the CLOSE transition is what releases a
        /// parked round (see <see cref="Apply"/>).</summary>
        private bool _wasOpen;

        private float RowHeight
        {
            get
            {
                if (_rowHeight > 1f)
                {
                    return _rowHeight;
                }

                float fromPrefab = _rowPrefab != null
                    ? ((RectTransform)_rowPrefab.transform).rect.height
                    : 0f;
                _rowHeight = fromPrefab > 1f ? fromPrefab : AdminStatsRow.Height;
                return _rowHeight;
            }
        }

        private void Start()
        {
            // ⚠️ No persistent onClick entries in the prefab (see AdminPreferencesPanel.WireButtons).
            // ⚠️ The button still only CLOSES: releasing a parked round hangs off the close transition in
            // Apply(), so the I key does exactly what the button does.
            Wire(_closeButton, AdminSession.ClosePanel);
            Wire(_calibrateAllButton, ReloadAllCalibrations);
            Wire(_measureAllButton, () => AdminCommands.MeasureBodyScale(0));
            Wire(_restartBodyAllButton, () => AdminCommands.RestartBodyTracking(0));
            Wire(_popupCloseButton, HidePopup);

            if (_root != null)
            {
                _root.SetActive(false); // Apply() decides visibility
            }

            HidePopup();
            Apply();
        }

        private static void Wire(UiButtonStyle style, UnityEngine.Events.UnityAction action)
        {
            Wire(style != null ? style.TargetButton : null, action);
        }

        private static void Wire(Button button, UnityEngine.Events.UnityAction action)
        {
            if (button == null)
            {
                return;
            }

            button.onClick.RemoveAllListeners();
            button.onClick.AddListener(action);
        }

        private void OnEnable()
        {
            AdminSession.Changed += MarkDirty;
            AdminRoster.CalibrationResult += HandleCalibrationResult;

            if (AdminRoster.Instance != null)
            {
                AdminRoster.Instance.Changed += MarkDirty;
            }
        }

        private void OnDisable()
        {
            AdminSession.Changed -= MarkDirty;
            AdminRoster.CalibrationResult -= HandleCalibrationResult;

            if (AdminRoster.Instance != null)
            {
                AdminRoster.Instance.Changed -= MarkDirty;
            }
        }

        private void Update()
        {
            bool tick = Time.unscaledTime >= _nextRefresh;
            if (tick)
            {
                _nextRefresh = Time.unscaledTime + RefreshInterval;
            }

            if (_dirty || tick)
            {
                _dirty = false;
                Apply();
            }

            // Confirm windows and the calibration timeout advance PER FRAME: on the refresh
            // interval the countdown would twitch in half-second steps.
            for (int i = 0; i < _live.Count; i++)
            {
                _live[i].Tick();
            }

            if (_popupUntil >= 0f && Time.unscaledTime >= _popupUntil)
            {
                HidePopup();
            }
        }

        private void MarkDirty()
        {
            _dirty = true;
        }

        // ------------------------------------------------------------------ refresh

        private void Apply()
        {
            if (_root == null)
            {
                return;
            }

            bool open = AdminSession.OpenPanel == AdminPanelKind.Stats;
            bool waiting = RoundReviewWaiting();

            // ⚠️ CLOSING the panel IS the operator's "carry on" for a parked round (§10.5): the round
            // stopped precisely so this table could be read, so putting it away is them saying they are
            // done. Hung off the transition rather than the close button, so the `I` key means the same
            // thing — and read BEFORE anything else, while `waiting` still describes the server the
            // operator was looking at.
            if (_wasOpen && !open && waiting)
            {
                AdminCommands.ModeContinue();
            }

            _wasOpen = open;

            if (_root.activeSelf != open)
            {
                _root.SetActive(open);

                // Always opens at the TOP of the list: a carried-over scroll position could land
                // the operator in empty space after the list shrank.
                if (open && _scroll != null)
                {
                    _scroll.verticalNormalizedPosition = 1f;
                }
            }

            ApplyCloseButton(waiting);

            AdminRoster roster = AdminRoster.Instance;
            if (!open || roster == null)
            {
                return;
            }

            bool teams = !roster.IsFfa;

            RefreshHeader(roster, teams);
            RefreshRows(roster, teams);
            RefreshKillDeathHeaders();
            RefreshMatchInfo(roster);
        }

        /// <summary>Header: the mini scorebug in team modes, a one-line headline without
        /// teams.</summary>
        private void RefreshHeader(AdminRoster roster, bool teams)
        {
            SetActive(_scorebugRoot, teams);
            SetActive(_headline, !teams);

            if (teams)
            {
                if (_scoreRedText != null)
                {
                    _scoreRedText.text = roster.ScoreRed.ToString();
                }

                if (_scoreBlueText != null)
                {
                    _scoreBlueText.text = roster.ScoreBlue.ToString();
                }

                return;
            }

            if (_headline == null)
            {
                return;
            }

            // ⚠️ BEFORE the FFA branch: co-op is teamless too, but it has no leader — everyone feeds
            // one total, so a "LİDER" line would invent a contest the mode does not have.
            if (ModeRuntime.IsCoop)
            {
                _headline.text = $"EKİP TOPLAMI {roster.ScoreRed}";
                return;
            }

            IReadOnlyList<AdminPlayerView> ranked = OrderedPlayers(roster);
            _headline.text = ranked.Count > 0 && ranked[0].score > 0
                ? $"LİDER: {Girdap.Upper(ranked[0].name)} {ranked[0].score}"
                : "HERKES TEK";
        }

        /// <summary>Drops the K · D · K/D headers where the counters cannot mean anything (co-op,
        /// weaponless). ⚠️ Visibility is written on EVERY refresh, never only switched off: the panel
        /// survives the match, so a header hidden by a kids' mode would stay hidden for the next
        /// shooter match.</summary>
        private void RefreshKillDeathHeaders()
        {
            if (_killDeathHeaderCells == null)
            {
                return;
            }

            bool visible = !ModeRuntime.HidesCombatStats;
            for (int i = 0; i < _killDeathHeaderCells.Length; i++)
            {
                GameObject cell = _killDeathHeaderCells[i];
                if (cell != null && cell.activeSelf != visible)
                {
                    cell.SetActive(visible);
                }
            }
        }

        private static void SetActive(Component target, bool active)
        {
            if (target != null && target.gameObject.activeSelf != active)
            {
                target.gameObject.SetActive(active);
            }
        }

        private static void SetActive(GameObject target, bool active)
        {
            if (target != null && target.activeSelf != active)
            {
                target.SetActive(active);
            }
        }

        /// <summary>
        /// List order: team modes keep the roster order (playerId) so a player is always on the
        /// same row; without teams the only meaningful order is score, descending (stable on ties by
        /// playerId).
        /// </summary>
        private IReadOnlyList<AdminPlayerView> OrderedPlayers(AdminRoster roster)
        {
            if (!roster.IsFfa)
            {
                return roster.Players;
            }

            _sorted.Clear();
            for (int i = 0; i < roster.Players.Count; i++)
            {
                _sorted.Add(roster.Players[i]);
            }

            _sorted.Sort(CompareByScoreDescending);
            return _sorted;
        }

        private static int CompareByScoreDescending(AdminPlayerView a, AdminPlayerView b)
        {
            int byScore = b.score.CompareTo(a.score);
            return byScore != 0 ? byScore : a.playerId.CompareTo(b.playerId);
        }

        /// <summary>
        /// Fills the single table and drives the scroll content height.
        /// <para>⚠️ No filtering by connection state, ever (§10.2): a <c>left</c> row must appear in
        /// the end-of-match table — the server keeps it in the roster exactly for that.</para>
        /// <para>⚠️ No row COUNT cap either: unlike the HUD side columns nothing is clipped here, the
        /// content height is driven and the ScrollRect scrolls the rest. A clipped stats table
        /// would hide the player the operator is looking for.</para>
        /// </summary>
        private void RefreshRows(AdminRoster roster, bool teams)
        {
            if (_rowContainer == null)
            {
                return;
            }

            _live.Clear();

            float height = RowHeight;
            float step = height + _rowGap;
            float groupStep = GroupHeight + _rowGap;
            float y = 0f;
            int used = 0;

            SetActive(_redGroup, teams);
            SetActive(_blueGroup, teams);

            if (teams)
            {
                BuildRedSection(roster);

                PlaceGroup(_redGroup, y);
                FillGroup(roster, "red", _redGroupName, _redGroupMeta, _redGroupKills,
                    _redGroupDeaths, _redGroupScore, _redSection.Count, roster.ScoreRed);
                y += groupStep;
                y = FillRows(_redSection, ref used, y, step, height);

                PlaceGroup(_blueGroup, y);
                FillGroup(roster, "blue", _blueGroupName, _blueGroupMeta, _blueGroupKills,
                    _blueGroupDeaths, _blueGroupScore, roster.Blue.Count, roster.ScoreBlue);
                y += groupStep;
                y = FillRows(roster.Blue, ref used, y, step, height);
            }
            else
            {
                y = FillRows(OrderedPlayers(roster), ref used, y, step, height);
            }

            for (int i = used; i < _rows.Count; i++)
            {
                _rows[i].SetVisible(false);
            }

            // Content height is driven from code: no ContentSizeFitter/Layout Group (kit layout
            // rule) — the scrollbar range comes from here alone. The trailing gap is dropped.
            _rowContainer.SetSizeWithCurrentAnchors(RectTransform.Axis.Vertical,
                Mathf.Max(0f, y - _rowGap));
        }

        private static void PlaceGroup(RectTransform group, float top)
        {
            if (group == null)
            {
                return;
            }

            group.anchorMin = new Vector2(0f, 1f);
            group.anchorMax = new Vector2(1f, 1f);
            group.pivot = new Vector2(0.5f, 1f);
            group.offsetMin = new Vector2(0f, -(top + GroupHeight));
            group.offsetMax = new Vector2(0f, -top);
        }

        /// <summary>Team group row: name (plus the team-less note), player/alive counts and the
        /// team's kill · death · score totals.</summary>
        private void FillGroup(AdminRoster roster, string team, TextMeshProUGUI name,
            TextMeshProUGUI meta, TextMeshProUGUI kills, TextMeshProUGUI deaths,
            TextMeshProUGUI score, int shown, int teamScore)
        {
            roster.TeamTotals(team, out int teamKills, out int teamDeaths, out int teamAlive);

            bool red = team == "red";

            if (name != null)
            {
                name.text = red ? "KIRMIZI" : "MAVİ";
            }

            if (meta != null)
            {
                // Weaponless team mode: nobody shoots and nobody dies, so an "alive" count would be
                // a number the operator has to learn to ignore.
                string counts = ModeRuntime.IsWeaponless
                    ? $"{shown} oyuncu"
                    : $"{shown} oyuncu · {teamAlive} canlı";
                // ⚠️ The team-less are counted OUT LOUD: they are drawn under the red group but are
                // not red, and a silent list would claim they are.
                int loose = red ? shown - roster.Red.Count : 0;
                meta.text = loose > 0 ? $"{counts} · +{loose} takımsız" : counts;
            }

            bool combat = !ModeRuntime.HidesCombatStats;
            SetActive(kills, combat);
            SetActive(deaths, combat);

            if (kills != null)
            {
                kills.text = teamKills.ToString();
            }

            if (deaths != null)
            {
                deaths.text = teamDeaths.ToString();
            }

            if (score != null)
            {
                score.text = teamScore.ToString();
            }
        }

        /// <summary>
        /// Places and binds one section of the table from the shared pool; returns the next free y.
        /// <para>⚠️ Every bound row is appended to <see cref="_live"/> — a row left out of it stops
        /// ticking, so its armed confirm window would never expire.</para>
        /// </summary>
        private float FillRows(IReadOnlyList<AdminPlayerView> players, ref int used, float y,
            float step, float height)
        {
            if (players == null)
            {
                return y;
            }

            for (int i = 0; i < players.Count; i++)
            {
                AdminStatsRow row = Take(used);
                if (row == null)
                {
                    break;
                }

                used++;
                row.SetVisible(true);
                row.Place(y, height);
                row.Bind(players[i], players[i].playerId == AdminSession.SelectedPlayerId);
                _live.Add(row);
                y += step;
            }

            return y;
        }

        private AdminStatsRow Take(int index)
        {
            while (_rows.Count <= index)
            {
                if (_rowPrefab == null || _rowContainer == null)
                {
                    Debug.LogWarning("[AdminStatsPanel] Satır prefabı atanmadı; oyuncu satırları çizilemiyor.");
                    return null;
                }

                AdminStatsRow row = Instantiate(_rowPrefab, _rowContainer);
                row.Initialize(HandleRowSelected, ShowPopup);
                _rows.Add(row);
            }

            return _rows[index];
        }

        /// <summary>
        /// Red section of a team mode: red first, then the team-less.
        /// <para>⚠️ The team-less are <b>not</b> dropped, unlike the HUD side columns: this is the
        /// screen where calibration and naming happen, and in Lobby — before the server hands out
        /// teams — every player is team-less, so filtering by team alone would leave the operator
        /// with an empty table exactly when the work has to be done. Their row keeps its neutral
        /// number plate and the group row counts them, so the table never claims they are red.</para>
        /// </summary>
        private void BuildRedSection(AdminRoster roster)
        {
            _redSection.Clear();

            for (int i = 0; i < roster.Red.Count; i++)
            {
                _redSection.Add(roster.Red[i]);
            }

            for (int i = 0; i < roster.Players.Count; i++)
            {
                AdminPlayerView view = roster.Players[i];
                if (view.team != "red" && view.team != "blue")
                {
                    _redSection.Add(view);
                }
            }
        }

        /// <summary>Is the server parked on a closed round waiting for the operator (§10.5)?</summary>
        /// <remarks>⚠️ Keyed on <c>modeState</c>, never on <c>modeId</c>: the vocabulary belongs to the
        /// mode (§10.1), so a hardcoded "tournament" here would go stale the day a second round-based
        /// mode lands — and would be a second place deciding what a mode string means.</remarks>
        private static bool RoundReviewWaiting()
        {
            AdminRoster roster = AdminRoster.Instance;
            return roster != null &&
                   roster.Phase == ArenaProtocol.PHASE_PAUSED &&
                   roster.PhaseReason == ArenaProtocol.PAUSE_REASON_MODE &&
                   roster.ModeState.StartsWith("roundend:", StringComparison.Ordinal);
        }

        /// <summary>Renames the close button while a round is parked: closing the panel is what releases
        /// it, so the button has to say so rather than look like a plain dismiss.</summary>
        /// <remarks>The label slot was measured for the LONGER text, so no resize is needed — a
        /// growing button would push its own icon and keycap out of place.</remarks>
        private void ApplyCloseButton(bool waiting)
        {
            if (_closeButton != null)
            {
                _closeButton.SetLabel(waiting ? "TURA DEVAM" : "KAPAT");
                _closeButton.SetKind(waiting ? UiButtonKind.Go : UiButtonKind.Normal);
            }

            if (_footHint != null)
            {
                // Says out loud that the arena is stopped ON PURPOSE and names the way out: a parked
                // round has no timer, so a silent panel would read as a hang.
                _footHint.text = waiting
                    ? "TUR SONU — akış bekliyor: paneli kapatmak sıradaki tura geçirir " +
                      "(diğer çıkışlar: maçı bitir, maçı iptal et)."
                    : "";
                SetActive(_footHint, waiting);
            }
        }

        private void RefreshMatchInfo(AdminRoster roster)
        {
            ArenaClient client = ArenaClient.Instance;
            string endpoint = client != null && client.IsConnected
                ? $"{client.ServerIp}:{client.ServerPort}"
                : "bağlı değil";
            float age = roster.SnapshotAge;

            SetInfo(InfoPhase, PhaseLabel(roster.Phase, roster.PhaseReason));
            SetInfo(InfoRemaining, FormatTime(roster.TimeRemaining));
            SetInfo(InfoMode, string.IsNullOrEmpty(roster.ModeId)
                ? "-"
                : AdminContent.ModeDisplayName(roster.ModeId));
            SetInfo(InfoMap, string.IsNullOrEmpty(roster.SceneName) ? "-" : roster.SceneName);
            // Duration/limit can be per match (§5.2), so this is where the operator verifies the
            // chosen value was really applied; both slots vanish when the server sends none.
            SetInfo(InfoDuration, roster.RoundSeconds > 0
                ? AdminCommands.FormatDuration(roster.RoundSeconds)
                : null);
            // The limit is three-valued (§5.2) and is written for unlimited too: "no limit line"
            // and "limit is unlimited" must be distinguishable.
            SetInfo(InfoScoreLimit, roster.ScoreLimit != 0
                ? AdminCommands.FormatScoreLimit(roster.ScoreLimit)
                : null);
            SetInfo(InfoServer, endpoint);
            SetInfo(InfoSnapshot, age >= 0f ? $"{age:0.0} sn önce" : "yok");
            SetInfo(InfoAdmins, roster.AdminCount.ToString());
            // Co-op customer counters, when the running mode publishes them (`h:`/`u:` in
            // modeState): the operator must read the same numbers the players see on their HUD.
            // Parsing lives in AdminModeState — a second parser here would be a second set of
            // numbers.
            SetInfo(InfoCustomers,
                AdminModeState.TryCustomerCounts(roster.ModeState, out int happy, out int unhappy)
                    ? $"mutlu {happy} · mutsuz {unhappy}"
                    : null);

            LayoutInfoStrip();
        }

        /// <summary>Writes one info slot; <c>null</c> hides the whole label+value pair.</summary>
        private void SetInfo(int index, string value)
        {
            if (_infoItems == null || index >= _infoItems.Length)
            {
                return;
            }

            bool visible = value != null;
            SetActive(_infoItems[index], visible);

            if (visible && _infoValues != null && index < _infoValues.Length &&
                _infoValues[index] != null)
            {
                _infoValues[index].text = value;
            }
        }

        /// <summary>
        /// Flows the visible info pairs left to right.
        /// <para>⚠️ Measured here, not laid out: values change length (ping, endpoint, remaining
        /// time) and the kit forbids Layout Groups, so the strip would otherwise either overlap or
        /// leave holes where a pair is hidden.</para>
        /// </summary>
        private void LayoutInfoStrip()
        {
            if (_infoItems == null)
            {
                return;
            }

            float x = 0f;
            for (int i = 0; i < _infoItems.Length; i++)
            {
                RectTransform item = _infoItems[i];
                if (item == null || !item.gameObject.activeSelf)
                {
                    continue;
                }

                TextMeshProUGUI value = _infoValues != null && i < _infoValues.Length
                    ? _infoValues[i]
                    : null;

                float width = 0f;
                if (value != null)
                {
                    float textWidth = Mathf.Ceil(value.GetPreferredValues(value.text).x);
                    RectTransform rect = value.rectTransform;
                    rect.sizeDelta = new Vector2(textWidth, rect.sizeDelta.y);
                    // The label's own width is baked into the value's x offset by the builder.
                    width = rect.anchoredPosition.x + textWidth;
                }

                item.anchoredPosition = new Vector2(x, item.anchoredPosition.y);
                item.sizeDelta = new Vector2(width, item.sizeDelta.y);
                x += width + InfoGap;
            }
        }

        /// <summary>
        /// Turkish name of the arena's state (§10.1) for the info strip.
        /// <para>⚠️ <b>The REASON is part of the name:</b> there are only three phases, and lobby,
        /// scene loading and countdown are all <c>paused</c>. Printing "duraklatıldı" for them would
        /// read as "somebody stopped the match" in states where nothing has started yet.</para>
        /// <para>⚠️ <b>An unknown phase is shown RAW</b>, never mapped to a guess: the server may
        /// add one, and a silent fallback would tell the operator the arena is in a state it is
        /// not. An unknown <i>reason</i> falls back to the plain pause — it is still a pause.</para>
        /// </summary>
        private static string PhaseLabel(string phase, string reason)
        {
            if (phase == ArenaProtocol.PHASE_PLAYING)
            {
                return "oynanıyor";
            }

            if (phase == ArenaProtocol.PHASE_FINISHED)
            {
                return "bitti";
            }

            if (phase != ArenaProtocol.PHASE_PAUSED)
            {
                return phase;
            }

            switch (reason)
            {
                case ArenaProtocol.PAUSE_REASON_LOBBY: return "lobi";
                case ArenaProtocol.PAUSE_REASON_LOADING: return "yükleniyor";
                case ArenaProtocol.PAUSE_REASON_COUNTDOWN: return "geri sayım";
                // The mode's own reason lives in modeState; the strip only says who stopped it.
                case ArenaProtocol.PAUSE_REASON_MODE: return "mod duraklattı";
                // PAUSE_REASON_OPERATOR and an empty/unknown reason are both the plain pause.
                default: return "duraklatıldı";
            }
        }

        private static string FormatTime(float seconds)
        {
            int total = Mathf.Max(0, Mathf.CeilToInt(seconds));
            return $"{total / 60:00}:{total % 60:00}";
        }

        // ------------------------------------------------------------- bulk actions

        /// <summary>
        /// Reloads everyone's calibration from the headset record.
        /// <para>⚠️ <b>Order matters:</b> rows go into loading state FIRST, the command second. The
        /// other way round, a headset answering instantly would reply before the row is in loading
        /// state and the result would be swallowed unseen.</para>
        /// <para>No confirm window: reloading benches nobody and leaves the player as before if it
        /// fails — an undoable attempt, unlike a reset.</para>
        /// </summary>
        private void ReloadAllCalibrations()
        {
            for (int i = 0; i < _live.Count; i++)
            {
                _live[i].BeginCalibrationLoad();
            }

            AdminCommands.ReloadCalibration(0);
        }

        // ------------------------------------------------------------- callbacks

        private void HandleRowSelected(int playerId)
        {
            AdminSession.SelectedPlayerId = playerId;
        }

        /// <summary>Hands the result to <b>that row only</b>: the message is an event, no relayout
        /// needed.</summary>
        private void HandleCalibrationResult(CalibrationResultMsg msg)
        {
            if (msg == null)
            {
                return;
            }

            for (int i = 0; i < _live.Count; i++)
            {
                if (_live[i].PlayerId == msg.playerId)
                {
                    _live[i].ApplyCalibrationResult(msg.ok, msg.error);
                    return;
                }
            }
        }

        /// <summary>
        /// Shows why a calibration reload failed as a toast (the narrow row button can only carry
        /// "HATA"; the row keeps the reason in its violation cell).
        /// <para>⚠️ The panel is not locked behind it and the toast auto-closes: the operator can
        /// keep working, and clicking it dismisses it early.</para>
        /// </summary>
        private void ShowPopup(int playerId, string error)
        {
            if (_popupRoot == null)
            {
                return;
            }

            if (_popupText != null)
            {
                AdminRoster roster = AdminRoster.Instance;
                string who = roster != null ? roster.NameOf(playerId) : $"Oyuncu {playerId}";
                _popupText.text = $"{who} · {error}";
                LayoutToast();
            }

            if (_popupIcon != null)
            {
                // Ink colour of the warning fill, same as the label — the glyph is part of the
                // sentence, not a separate severity channel.
                _popupIcon.color = Girdap.ConfirmFg;
            }

            _popupRoot.SetActive(true);
            _popupUntil = Time.unscaledTime + PopupSeconds;
        }

        /// <summary>Hugs the toast to its text (CSS <c>.toast</c> is inline-flex, and this kit has
        /// no Layout Group).</summary>
        private void LayoutToast()
        {
            if (_popupShape == null || _popupText == null)
            {
                return;
            }

            float textWidth = Mathf.Ceil(_popupText.GetPreferredValues(_popupText.text).x);
            RectTransform textRect = _popupText.rectTransform;
            textRect.sizeDelta = new Vector2(textWidth, textRect.sizeDelta.y);
            _popupShape.sizeDelta = new Vector2(
                ToastPadding * 2f + ToastIcon + ToastGap + textWidth, _popupShape.sizeDelta.y);
        }

        private void HidePopup()
        {
            _popupUntil = -1f;

            if (_popupRoot != null && _popupRoot.activeSelf)
            {
                _popupRoot.SetActive(false);
            }
        }
    }
}
