using System;
using System.Text;
using TMPro;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;
using VortexArena.Core.UI;
using VortexArena.Protocol;

namespace VortexArena.App.Admin
{
    /// <summary>
    /// Single player card in the side columns (CSS <c>.pcard</c>): jersey number plate, name +
    /// <c>#id</c> + status chip, HP, telemetry and five actions (POV · ÖLÇ · takım · SIFIRLA · AT).
    /// <para>
    /// <b>Look comes from the prefab</b> (<c>Assets/_Shared/App/Resources/UI/AdminPlayerRow.prefab</c>,
    /// generated by <c>GirdapUiBuilder.BuildPlayerRow</c>); this class is behaviour only. Unbound
    /// fields silently draw nothing — keep prefab wiring intact.
    /// </para>
    /// <para>Kick is two-step (<see cref="ConfirmSeconds"/>): taking a player out of the fight must
    /// not happen on one stray click.</para>
    /// <para>⚠️ SIFIRLA is the SAME command and grammar as the stats row's (<see cref="HoldButton"/>):
    /// a tap voids the alignment and keeps the saved anchor, a 1 s hold wipes that anchor too. One
    /// button, two screens — never a different meaning per screen. Reload (KALİBRE) stays in the
    /// stats panel only.</para>
    /// </summary>
    public class AdminPlayerRow : MonoBehaviour
    {
        /// <summary>Card height <b>fallback</b> (px, CSS <c>.pcard</c>); real height is read from the
        /// prefab's <see cref="RectTransform"/> (<see cref="AdminHud"/>) so resizing it in the prefab
        /// reflows the column.</summary>
        public const float Height = 136f;

        /// <summary>Confirm window (s) of the "AT" button. ⚠️ SIFIRLA does NOT use it — its friction
        /// is the hold (<see cref="HoldButton"/>).</summary>
        private const float ConfirmSeconds = 3f;

        /// <summary>How long <see cref="LabelPurged"/> stays up (s) — same as the stats row.</summary>
        private const float PurgedHoldSeconds = 2f;

        private const string LabelConfirm = "EMİN?";
        private const string LabelReset = "SIFIRLA";

        /// <summary>SIFIRLA while the hard-reset hold is running. ⚠️ Names what is being DESTROYED,
        /// not "keep holding": the operator must be able to abort by reading the button.</summary>
        private const string LabelPurging = "SİLİNİYOR";

        /// <summary>Shown right after the saved anchor is wiped. ⚠️ Required: without it the button
        /// snaps back to SIFIRLA and a completed wipe reads like one aborted by sliding off.</summary>
        private const string LabelPurged = "SİLİNDİ";

        /// <summary>ÖLÇ button for a not-yet-measured player.</summary>
        private const string LabelMeasure = "ÖLÇ";

        /// <summary>Last measurement failed (§10.8): says so instead of a scale, so the operator
        /// does not read "pressed it and nothing happened". ⚠️ Short, not "ÖLÇÜLEMEDİ": five
        /// action columns leave ~63 px and the long word overflows into its neighbours.</summary>
        private const string LabelMeasureFailed = "HATA";

        private const string TeamRed = "red";
        private const string TeamBlue = "blue";

        /// <summary>Headset battery warning thresholds (0..1) — an OPERATOR call: 25% "swap before
        /// the session ends", 50% "keep an eye on it". Shared with the stats panel through
        /// <see cref="FormatBattery"/> so the same battery never differs between screens.</summary>
        private const float BatteryCritical = 0.25f;

        /// <inheritdoc cref="BatteryCritical"/>
        private const float BatteryLow = 0.5f;

        /// <summary>Unknown battery/ping placeholder. ⚠️ Plain hyphen-minus, not an en dash: TMP's
        /// theme fonts do not guarantee the dash glyph and a miss draws □.</summary>
        private const string Unknown = "-";

        // ⚠️ ASCII controller glyphs for the stats panel's TEXT line (the card uses colored ticks):
        // ●/◐/✕ are not guaranteed in the theme fonts. COLOUR carries the distinction; the letter is
        // only a fallback for a colour-blind operator.
        private const string GlyphControllerOk = "+";
        private const string GlyphControllerUntracked = "~";
        private const string GlyphControllerLost = "X";
        private const string GlyphControllerUnknown = "-";
        private const string GlyphBodyFallback = "T";

        /// <summary>Card dimming (CSS <c>.pcard.away &gt; *</c>): a device expected back must not
        /// look like one removed from the game (§2) — the first may return, the second needs no
        /// action, so "left" is dimmed one grade further.</summary>
        private const float ReconnectingAlpha = 0.55f;

        /// <inheritdoc cref="ReconnectingAlpha"/>
        private const float LeftAlpha = 0.45f;

        /// <summary>Dead number plate (CSS <c>filter: saturate(.45) brightness(.6)</c>, approximated
        /// by a flat multiply — uGUI has no filter).</summary>
        private const float DeadPlateScale = 0.6f;

        /// <summary>Violation blink (CSS <c>animation: bring 1s steps(2)</c>).
        /// <para>⚠️ <b>Phase is NOT offset per card</b> (<c>Time.unscaledTime</c> only): synchronous
        /// blinking lets the operator count violations at a glance.</para></summary>
        private const float AlertBlinkHz = 1f;

        /// <summary>CSS <c>.pcard.alert --bw</c>.</summary>
        private const float AlertBorderWidth = 2f;

        private const float CardBorderWidth = 1f;

        /// <summary>HP thresholds of CSS <c>hpc()</c>, normalized.</summary>
        private const float HpWarn = 0.5f;

        /// <inheritdoc cref="HpWarn"/>
        private const float HpBad = 0.2f;

        /// <summary>CSS <c>.pc-tele</c> gap between groups / inside a group.</summary>
        private const float TeleGap = 14f;

        /// <inheritdoc cref="TeleGap"/>
        private const float TeleInnerGap = 4f;

        private const float TeleIconSize = 16f;

        /// <summary>CSS <c>.ctrl i</c> tick and the gap between the two hands.</summary>
        private const float CtrlDotWidth = 9f;

        /// <inheritdoc cref="CtrlDotWidth"/>
        private const float CtrlDotGap = 3f;

        /// <summary>CSS <c>.pc-top</c> gap (name · #id · chip).</summary>
        private const float TopGap = 8f;

        /// <summary>CSS <c>.pcard</c> resting border.</summary>
        private static readonly Color CardBorder = Girdap.CardBd;

        /// <summary>CSS <c>@keyframes bring</c>: the alert outline flashes to a near-transparent
        /// red instead of going dark, so "how many are in violation" stays countable.</summary>
        private static readonly Color AlertDim =
            new Color(Girdap.Bad.r, Girdap.Bad.g, Girdap.Bad.b, 0.28f);

        /// <summary>CSS <c>.pcard.sel::after</c> inset glow.</summary>
        private static readonly Color SelectionGlow =
            new Color(Girdap.Acc.r, Girdap.Acc.g, Girdap.Acc.b, 0.30f);

        /// <summary>CSS <c>.pcard.sel::after</c> blur radius.</summary>
        private const float SelectionGlowWidth = 24f;

        /// <summary>Card bed (CSS <c>.pcard --bg</c> second layer) — the team wash fades into this
        /// at 48%.</summary>
        private static readonly Color CardBed =
            new Color(Girdap.PanelB.r, Girdap.PanelB.g, Girdap.PanelB.b, 0.95f);

        /// <summary>CSS <c>.pcard --bg</c> gradient stop.</summary>
        private const float CardWashStop = 0.48f;

        [Header("Kart")]
        [Tooltip("Kart yüzeyi: kenarlık (seçim/uyarı/kalibresiz) ve takım yıkaması bunun üstünde.")]
        [SerializeField] private UiShape cardShape;
        [Tooltip("Kartın tamamı seçim düğmesidir; yüzey raycast'i buna baloncuklanır.")]
        [SerializeField] private Button selectButton;
        [Tooltip("Bağlantısı düşen/ayrılan kartın soldurulması (CSS .away).")]
        [SerializeField] private CanvasGroup dimGroup;
        [Tooltip("Sol kenardaki forma numarası plakası.")]
        [SerializeField] private UiShape numberPlate;
        [SerializeField] private TextMeshProUGUI numberText;

        [Header("Üst satır")]
        [Tooltip("Ad/#id/çip ölçülerek yerleşir — satır genişliği kolona göre değişir.")]
        [SerializeField] private RectTransform topRow;
        [SerializeField] private TextMeshProUGUI nameText;
        [SerializeField] private TextMeshProUGUI idText;
        [SerializeField] private UiChip statusChip;

        [Header("Can")]
        [SerializeField] private TextMeshProUGUI hpText;
        [SerializeField] private UiSegmentBar hpBar;

        [Header("Telemetri")]
        [SerializeField] private RectTransform teleRow;
        [SerializeField] private TextMeshProUGUI kdLabel;
        [SerializeField] private TextMeshProUGUI kdText;
        [SerializeField] private Image batteryIcon;
        [SerializeField] private TextMeshProUGUI batteryText;
        [SerializeField] private UiSegmentBar ctrlLeftDot;
        [SerializeField] private UiSegmentBar ctrlRightDot;
        [SerializeField] private Image bodyIcon;

        [Header("Eylem düğmeleri")]
        [SerializeField] private UiButtonStyle povButton;
        [Tooltip("Gövde ölçüsünü aldırır (§10.8). Etiketi aynı zamanda GÖSTERGEDİR: " +
                 "ölçülmemişse 'ÖLÇ', ölçülmüşse çarpan.")]
        [SerializeField] private UiButtonStyle measureButton;
        [SerializeField] private UiButtonStyle teamButton;
        [Tooltip("Kalibrasyonu sıfırlar — TEK düğme: kısa basış o anki hizalamayı düşürür, " +
                 "1 sn basılı tutmak gözlükteki KAYITLI çapayı da sildirir (ardından KALİBRE iş " +
                 "görmez, oyuncu elle A/B almak zorunda kalır).")]
        [SerializeField] private UiButtonStyle resetButton;
        [SerializeField] private UiButtonStyle kickButton;

        private RectTransform _rect;
        private Action<int> _onSelect;
        private Action<int> _onPov;

        private int _playerId;
        private string _team = "";
        private float _kickArmedAt = -1f;

        /// <summary>Press-duration gate of SIFIRLA; null when the button is unwired.</summary>
        private HoldButton _resetHold;

        /// <summary>Was SIFIRLA painted in its hold/result look last frame — without it the button
        /// would stay red after the press ends (<see cref="Tick"/> repaints only while needed).</summary>
        private bool _resetHoldPainted;

        /// <summary>When the saved anchor was wiped (<c>Time.unscaledTime</c>); &lt; 0 = no
        /// confirmation showing.</summary>
        private float _purgedAt = -1f;

        /// <summary>Card state outside a violation — cached because the blink repaints the outline
        /// every frame and needs a look to return to (<see cref="Bind"/> only runs on the refresh
        /// tick, so the card would stay frozen red).</summary>
        private bool _selected;

        /// <inheritdoc cref="_selected"/>
        private bool _uncalibrated;

        /// <summary>Was the outline painted in its alert look last frame; without it the card would
        /// stay red after the violation ends.</summary>
        private bool _alertPainted;

        /// <summary>Last painted blink half period (1 lit, 0 dim, -1 not alerting).</summary>
        private int _alertPhase = -1;

        private RectTransform Rect => _rect != null ? _rect : _rect = (RectTransform)transform;

        /// <summary>
        /// Wires button callbacks. ⚠️ No <c>onClick</c> entries in the prefab: the target player
        /// changes on every <see cref="Bind"/>, so a persistent entry would command the wrong one.
        /// </summary>
        public void Initialize(Action<int> onSelect, Action<int> onPov)
        {
            _onSelect = onSelect;
            _onPov = onPov;

            Wire(selectButton, () => _onSelect?.Invoke(_playerId));
            Wire(povButton, () => _onPov?.Invoke(_playerId));
            // ⚠️ One step (no confirm): measuring is undoable — a stray press is fixed by measuring
            // again. It is not an "out of the fight" command like AT.
            Wire(measureButton, () => AdminCommands.MeasureBodyScale(_playerId));
            Wire(teamButton, ToggleTeam);
            Wire(kickButton, PressKick);
            // ⚠️ NOT Wire(): onClick fires on pointer-up whatever the duration, so a completed hold
            // would also send the soft reset — the player would be reset twice.
            _resetHold = HoldButton.Attach(resetButton != null ? resetButton.TargetButton : null,
                PressReset, PressPurge);
            RefreshResetButton();
        }

        private static void Wire(UiButtonStyle style, UnityAction action)
        {
            Wire(style != null ? style.TargetButton : null, action);
        }

        private static void Wire(Button button, UnityAction action)
        {
            if (button == null)
            {
                return;
            }

            button.onClick.RemoveAllListeners();
            button.onClick.AddListener(action);
        }

        /// <summary>Binds the card to a player (called on every refresh).</summary>
        public void Bind(AdminPlayerView view, bool selected)
        {
            if (view == null)
            {
                return;
            }

            // ⚠️ A pooled card rebinds to ANOTHER player: a leftover armed "EMİN?" or a running
            // hold would land on whoever lands here next.
            if (_playerId != view.playerId)
            {
                _kickArmedAt = -1f;
                _resetHold?.Cancel();
                _purgedAt = -1f;
            }

            _playerId = view.playerId;
            _team = view.team;
            _selected = selected;
            _uncalibrated = view.NeedsCalibration;

            BindPlate(view);
            BindTop(view);
            BindHp(view);
            BindTelemetry(view);
            BindActions(view, selected);

            // Graded dimming: connected 1.0, expected back 0.55, left 0.45 — "may return" and "gone"
            // are two different operator decisions.
            if (dimGroup != null)
            {
                dimGroup.alpha = view.IsConnected ? 1f
                    : view.IsReconnecting ? ReconnectingAlpha : LeftAlpha;
            }

            RefreshKickButton();
            RefreshResetButton();
            ApplyWash();
            ApplyBorder(AdminViolations.Of(_playerId) != AdminViolationKind.None, force: true);
        }

        private void BindPlate(AdminPlayerView view)
        {
            if (numberPlate != null)
            {
                numberPlate.Fill(Girdap.TeamHi(view.team), Girdap.TeamLo(view.team),
                    UiGradientMode.Vertical);
                // Graphic.color multiplies the mesh gradient — the CSS filter on a dead plate.
                numberPlate.color = view.alive
                    ? Color.white
                    : new Color(DeadPlateScale, DeadPlateScale, DeadPlateScale, 1f);
            }

            if (numberText != null)
            {
                // 0 = unassigned (always so for admins): the plate stays blank rather than claiming
                // a number nobody wears.
                numberText.text = view.number > 0 ? view.number.ToString() : "";
            }
        }

        /// <summary>
        /// Name · <c>#id</c> · status chip. Measured, not laid out: the card is stretched to the
        /// column's width at runtime and the kit forbids Layout Groups, so the name gets whatever
        /// the chip and the id leave over and ellipsises there.
        /// </summary>
        private void BindTop(AdminPlayerView view)
        {
            SetStatusChip(view);

            if (nameText != null)
            {
                // Name drawn in TEAM COLOUR: the same name also appears on the scene label, the
                // top-down marker and the kill feed, and one colour everywhere answers "which team"
                // without reading. ⚠️ Teamless (FFA) carries no colour information — the title
                // colour stays. CSS `.pcard.dead .pc-name` wins over the team colour.
                nameText.color = !view.alive ? Girdap.Faint
                    : IsTeamPlayer(view.team) ? Girdap.TeamInk(view.team) : Girdap.Text;
                // ⚠️ NOT uppercased: CSS `.pc-name` has no text-transform, and the theme fonts'
                // Turkish lowercase is what the operator matches against the headset label.
                nameText.text = view.name;
            }

            if (idText != null)
            {
                idText.text = $"#{view.playerId}";
            }

            LayoutTop();
        }

        private void LayoutTop()
        {
            if (topRow == null || nameText == null)
            {
                return;
            }

            float chipWidth = statusChip != null && statusChip.Root != null
                ? statusChip.Root.sizeDelta.x
                : 0f;
            float idWidth = idText != null && !string.IsNullOrEmpty(idText.text)
                ? Mathf.Ceil(idText.GetPreferredValues(idText.text).x)
                : 0f;

            float available = topRow.rect.width - chipWidth - (chipWidth > 0f ? TopGap : 0f)
                              - idWidth - (idWidth > 0f ? TopGap : 0f);
            float nameWidth = Mathf.Clamp(
                Mathf.Ceil(nameText.GetPreferredValues(nameText.text).x), 0f, Mathf.Max(0f, available));

            SetX(nameText.rectTransform, 0f, nameWidth);
            if (idText != null)
            {
                SetX(idText.rectTransform, nameWidth + TopGap, idWidth);
            }
        }

        private void SetStatusChip(AdminPlayerView view)
        {
            if (statusChip == null)
            {
                return;
            }

            // ⚠️ KALİBRESİZ REPLACES every other state: an unaligned headset cannot play, so it is
            // the only thing the operator may read off the card.
            if (view.NeedsCalibration)
            {
                statusChip.Set("KALİBRESİZ", UiChipKind.Warn, "Warn");
                return;
            }

            if (view.IsReconnecting)
            {
                statusChip.Set($"YENİDEN BAĞLANIYOR · {view.ReconnectSecondsLeft} sn",
                    UiChipKind.Plain);
                return;
            }

            // There is no "offline" state (§2): a dropped device is either expected back or out.
            if (view.HasLeft)
            {
                statusChip.Set("AYRILDI", UiChipKind.Dead);
                return;
            }

            if (!view.alive)
            {
                float remaining = view.RespawnRemaining;
                if (remaining > 0.1f)
                {
                    statusChip.Set($"ÖLÜ {Mathf.CeilToInt(remaining)} sn", UiChipKind.Dead, "Skull");
                }
                else
                {
                    statusChip.Set("TABANDA BEKLENİYOR", UiChipKind.Dead);
                }

                return;
            }

            // A VIOLATION outranks HAZIR/BEKLİYOR (§10.9): one state slot, and the violation is the
            // actionable one. The live channel is the blinking outline; this names the kind.
            string violation = AdminViolations.Label(AdminViolations.Of(view.playerId));
            if (!string.IsNullOrEmpty(violation))
            {
                statusChip.Set(violation, UiChipKind.Bad, "Warn");
                return;
            }

            statusChip.Set(view.ready ? "HAZIR" : "BEKLİYOR",
                view.ready ? UiChipKind.Good : UiChipKind.Plain);
        }

        private void BindHp(AdminPlayerView view)
        {
            float normalized = view.HpNormalized;

            if (hpText != null)
            {
                hpText.text = Mathf.RoundToInt(view.hp).ToString();
                // ⚠️ Red only while still ALIVE but nearly out (CSS `hp > 0 && hp <= 20`): at 0 the
                // chip already says ÖLÜ, and a second red number only competes with it.
                hpText.color = view.hp > 0f && normalized <= HpBad ? Girdap.Bad : Girdap.Text;
            }

            if (hpBar != null)
            {
                hpBar.SetFill(normalized);
                if (normalized > HpWarn)
                {
                    hpBar.SetFillColors(Girdap.HpA, Girdap.Good);
                }
                else if (normalized > HpBad)
                {
                    hpBar.SetFillColors(Girdap.HpWarnA, Girdap.Warn);
                }
                else
                {
                    hpBar.SetFillColors(Girdap.HpBadA, Girdap.Bad);
                }
            }
        }

        /// <summary>K/D · headset battery · both controllers · body tracking, laid out left to
        /// right; an unknown token shrinks instead of leaving a gap.</summary>
        private void BindTelemetry(AdminPlayerView view)
        {
            Color ink = view.IsConnected ? Girdap.Muted : Girdap.Faint;

            if (kdLabel != null)
            {
                kdLabel.color = Girdap.Faint;
            }

            if (kdText != null)
            {
                kdText.text = $"{view.kills}/{view.deaths}";
                kdText.color = ink;
            }

            bool batteryKnown = view.battery >= 0f;
            if (batteryText != null)
            {
                float level = Mathf.Clamp01(view.battery);
                batteryText.text = batteryKnown ? $"%{Mathf.RoundToInt(level * 100f)}" : Unknown;
                // ⚠️ An unknown battery is NOT alarmed: sending the operator running on a value
                // nobody reported costs more than the warning saves.
                batteryText.color = !batteryKnown ? Girdap.Faint
                    : level < BatteryCritical ? Girdap.Bad
                    : level < BatteryLow ? Girdap.Warn
                    : ink;
            }

            if (batteryIcon != null)
            {
                SetShown(batteryIcon.gameObject, batteryKnown);
                batteryIcon.color = batteryText != null ? batteryText.color : ink;
            }

            SetControllerDot(ctrlLeftDot, view.ctrlL);
            SetControllerDot(ctrlRightDot, view.ctrlR);

            if (bodyIcon != null)
            {
                // ⚠️ The fault has NO local trace: the player's own screen looks normal, the T-pose
                // shows only on other screens (§5.1). This icon is the operator's only readout.
                bodyIcon.color = BodyColor(view.body);
            }

            LayoutTelemetry(batteryKnown);
        }

        private void LayoutTelemetry(bool batteryKnown)
        {
            if (teleRow == null)
            {
                return;
            }

            float x = 0f;

            if (kdLabel != null)
            {
                float w = Mathf.Ceil(kdLabel.GetPreferredValues(kdLabel.text).x);
                SetX(kdLabel.rectTransform, x, w);
                x += w + TeleInnerGap;
            }

            if (kdText != null)
            {
                float w = Mathf.Ceil(kdText.GetPreferredValues(kdText.text).x);
                SetX(kdText.rectTransform, x, w);
                x += w + TeleGap;
            }

            if (batteryIcon != null && batteryKnown)
            {
                SetX(batteryIcon.rectTransform, x, TeleIconSize);
                x += TeleIconSize + TeleInnerGap;
            }

            if (batteryText != null)
            {
                float w = Mathf.Ceil(batteryText.GetPreferredValues(batteryText.text).x);
                SetX(batteryText.rectTransform, x, w);
                x += w + TeleGap;
            }

            if (ctrlLeftDot != null)
            {
                SetX(ctrlLeftDot.rectTransform, x, CtrlDotWidth);
            }

            if (ctrlRightDot != null)
            {
                SetX(ctrlRightDot.rectTransform, x + CtrlDotWidth + CtrlDotGap, CtrlDotWidth);
            }

            x += CtrlDotWidth * 2f + CtrlDotGap + TeleGap;

            if (bodyIcon != null)
            {
                SetX(bodyIcon.rectTransform, x, TeleIconSize);
            }
        }

        private void BindActions(AdminPlayerView view, bool selected)
        {
            // POV is a toggle readout too: the card the operator is looking through lights up.
            if (povButton != null)
            {
                povButton.SetKind(selected ? UiButtonKind.On : UiButtonKind.Normal);
                povButton.SetInteractable(view.IsPlayer && !view.HasLeft);
            }

            RefreshMeasureButton(view);

            if (teamButton != null)
            {
                // Names the OTHER team (what will happen, not what is).
                // ⚠️ Not "MAVİYE"/"KIRMIZIYA": the narrow button row ellipsised the longer one.
                teamButton.SetLabel(view.team == TeamRed ? "MAVİ"
                    : view.team == TeamBlue ? "KIRMIZI" : "TAKIM");
                teamButton.SetKind(view.team == TeamRed ? UiButtonKind.TextBlue
                    : view.team == TeamBlue ? UiButtonKind.TextRed : UiButtonKind.Normal);
                // A left card has no command target (§10.2): the player is out, the card only
                // carries match stats. A dead press must not be mistaken for a sent command.
                teamButton.SetInteractable(!view.HasLeft);

                // TAKIM is HIDDEN in a teamless mode (§10.5 teamMode:"none"), not just dimmed: the
                // server rejects set_team there, so a visible button would read as "pressed it,
                // nothing happened". ⚠️ Same source as the column layout (AdminRoster.IsFfa) — a
                // second rule here would disagree with the panel on the lobby/match boundary.
                SetShown(teamButton.gameObject,
                    !(AdminRoster.Instance != null && AdminRoster.Instance.IsFfa));
            }

            if (kickButton != null)
            {
                kickButton.SetInteractable(!view.HasLeft);
            }

            // ⚠️ Disabled on a left card: the server only forwards the reset to a live connection,
            // so it would look sent and clear nothing.
            if (resetButton != null)
            {
                resetButton.SetInteractable(!view.HasLeft);
            }
        }

        /// <summary>Does the player have a team — team colour is meaningful only then.</summary>
        private static bool IsTeamPlayer(string team)
        {
            return team == TeamRed || team == TeamBlue;
        }

        private static void SetShown(GameObject go, bool value)
        {
            if (go != null && go.activeSelf != value)
            {
                go.SetActive(value);
            }
        }

        /// <summary>Left-anchored width/offset of an already middle-left anchored part.</summary>
        private static void SetX(RectTransform rt, float x, float width)
        {
            if (rt == null)
            {
                return;
            }

            rt.anchoredPosition = new Vector2(x, 0f);
            rt.sizeDelta = new Vector2(width, rt.sizeDelta.y);
        }

        private static void SetControllerDot(UiSegmentBar dot, int state)
        {
            if (dot == null)
            {
                return;
            }

            // ⚠️ No percentage possible: controller charge is unreadable under OpenXR on Quest
            // (§5.1). The actionable fact is "did this hand drop".
            Color c = state == ArenaProtocol.CONTROLLER_OK ? Girdap.Muted
                : state == ArenaProtocol.CONTROLLER_UNTRACKED ? Girdap.Warn
                : state == ArenaProtocol.CONTROLLER_LOST ? Girdap.Bad
                : Girdap.CtrlUnknown;
            dot.SetFillColors(c, c);
        }

        private static Color BodyColor(int state)
        {
            switch (state)
            {
                case ArenaProtocol.BODY_OK: return Girdap.Muted;
                case ArenaProtocol.BODY_FALLBACK: return Girdap.Warn;
                case ArenaProtocol.BODY_NO_PERMISSION: return Girdap.Bad;
                default: return Girdap.NeutralLo; // unreported — not shown as healthy
            }
        }

        /// <summary>Expires the kick confirm window, paints the reset hold and drives the violation
        /// blink (HUD calls every frame — both would otherwise step at the roster's 4 Hz).</summary>
        public void Tick()
        {
            if (_kickArmedAt >= 0f && Time.unscaledTime - _kickArmedAt > ConfirmSeconds)
            {
                _kickArmedAt = -1f;
                RefreshKickButton();
            }

            if (_resetHold != null && (_resetHold.IsPressed || _resetHoldPainted))
            {
                RefreshResetButton();
            }

            if (_purgedAt >= 0f)
            {
                // ⚠️ The window starts when the FINGER LIFTS: the wipe fires at the threshold while
                // the press is still on, so a window started there would expire under the thumb.
                if (_resetHold != null && _resetHold.IsPressed)
                {
                    _purgedAt = Time.unscaledTime;
                }
                else if (Time.unscaledTime - _purgedAt > PurgedHoldSeconds)
                {
                    _purgedAt = -1f;
                    RefreshResetButton();
                }
            }

            ApplyBorder(AdminViolations.Of(_playerId) != AdminViolationKind.None, force: false);
        }

        public void SetVisible(bool visible)
        {
            if (gameObject.activeSelf == visible)
            {
                return;
            }

            // ⚠️ An armed confirm or running hold is dropped: hidden cards stop ticking, and the
            // pooled card comes back bound to ANOTHER player — the next click would hit them.
            if (!visible)
            {
                _kickArmedAt = -1f;
                _resetHold?.Cancel();
                _purgedAt = -1f;
                RefreshKickButton();
                RefreshResetButton();
            }

            gameObject.SetActive(visible);
        }

        /// <summary>Places the card at the given top offset inside the column (full column width).</summary>
        public void Place(float top, float height)
        {
            RectTransform rt = Rect;
            rt.anchorMin = new Vector2(0f, 1f);
            rt.anchorMax = new Vector2(1f, 1f);
            rt.pivot = new Vector2(0.5f, 1f);
            rt.offsetMin = new Vector2(0f, -(top + height));
            rt.offsetMax = new Vector2(0f, -top);
        }

        // ---------------------------------------------------------------- internals

        /// <summary>
        /// Card surface: team wash + outline state.
        /// <para><b>Outline priority: violation &gt; selection &gt; uncalibrated &gt; normal.</b>
        /// Selection is already told twice (POV button, bottom panels) and a violation is what needs
        /// attention <i>now</i>; being uncalibrated is a one-off field job.</para>
        /// </summary>
        private void ApplyBorder(bool alert, bool force)
        {
            // ⚠️ Guarded: every Outline/InnerGlow call dirties the mesh, and Tick runs per frame —
            // repainting an unchanged outline would rebuild one card's geometry 90 times a second.
            int phase = alert
                ? (Mathf.Repeat(Time.unscaledTime * AlertBlinkHz, 1f) < 0.5f ? 1 : 0)
                : -1;
            if (!force && _alertPainted == alert && phase == _alertPhase)
            {
                return;
            }

            _alertPainted = alert;
            _alertPhase = phase;
            if (cardShape == null)
            {
                return;
            }

            if (alert)
            {
                cardShape.Outline(AlertBorderWidth, phase == 1 ? Girdap.Bad : AlertDim);
            }
            else if (_selected)
            {
                cardShape.Outline(CardBorderWidth, Girdap.Acc);
            }
            else if (_uncalibrated)
            {
                cardShape.Outline(CardBorderWidth, Girdap.Warn);
            }
            else
            {
                cardShape.Outline(CardBorderWidth, CardBorder);
            }

            cardShape.InnerGlow(_selected && !alert ? SelectionGlowWidth : 0f, SelectionGlow);
        }

        /// <summary>Team wash of the card bed (CSS <c>.pcard --bg</c>). Separate from the outline:
        /// it only changes on a rebind, while the alert outline blinks per frame.</summary>
        private void ApplyWash()
        {
            if (cardShape != null)
            {
                cardShape.Fill(CardWashA(_team), CardBed, UiGradientMode.Horizontal, CardWashStop);
            }
        }

        /// <summary>Team wash of the card bed. ⚠️ The two CSS background layers are flattened into
        /// one: a <see cref="UiShape"/> fill is a single gradient, not a stack.</summary>
        private static Color CardWashA(string team)
        {
            if (team == TeamRed)
            {
                return Color.Lerp(Girdap.Plate, Girdap.Red, 0.30f);
            }

            return team == TeamBlue ? Color.Lerp(Girdap.Plate, Girdap.Blue, 0.34f) : CardBed;
        }

        private void ToggleTeam()
        {
            // Teamless (FFA/new) player goes red: the server already balances, this is the
            // operator's manual override.
            string next = _team == TeamRed ? TeamBlue : TeamRed;
            AdminCommands.SetTeam(_playerId, next);
        }

        private void PressKick()
        {
            if (_kickArmedAt < 0f)
            {
                _kickArmedAt = Time.unscaledTime;
                RefreshKickButton();
                return;
            }

            _kickArmedAt = -1f;
            AdminCommands.Kick(_playerId);
            RefreshKickButton();
        }

        /// <summary>
        /// TAP: voids the current alignment and KEEPS the anchor saved on the headset (§5.2
        /// <c>clear_calibration</c>, soft mode) — KALİBRE puts the player back in one click.
        /// <para>⚠️ Sent even while the card reads KALİBRESİZ: that also covers a player stuck
        /// mid-sequence (A taken, B not), which the wire cannot tell apart from "never calibrated".</para>
        /// </summary>
        private void PressReset()
        {
            // A soft reset clears a standing "SİLİNDİ": the newer, weaker command is what happened.
            _purgedAt = -1f;
            AdminCommands.ClearCalibration(_playerId, keepSaved: true);
            RefreshResetButton();
        }

        /// <summary>HOLD (1 s): the same reset plus the headset's SAVED anchor (hard mode) — recovery
        /// becomes the manual A/B sequence in the headset. The hold IS the confirmation.</summary>
        private void PressPurge()
        {
            _purgedAt = Time.unscaledTime;
            AdminCommands.ClearCalibration(_playerId, keepSaved: false);
            RefreshResetButton();
        }

        /// <summary>
        /// ÖLÇ is both COMMAND and INDICATOR (§10.8): "ÖLÇ" when unmeasured, the scale itself when
        /// measured — the operator reads who is measured off the list, not by trial.
        /// <para>Disabled for an uncalibrated or absent player (the server rejects it anyway,
        /// measurement is relative to the arena floor) — a dead button feels like "sent but nothing
        /// happened".</para>
        /// <para>⚠️ On failure (<c>scaleError</c> set) the label says so and the button stays
        /// ENABLED: re-measuring is exactly the job. The reason itself lives in the notice line.</para>
        /// </summary>
        private void RefreshMeasureButton(AdminPlayerView view)
        {
            if (measureButton == null)
            {
                return;
            }

            bool usable = view.IsPlayer && view.calibrated && view.IsConnected;
            bool failed = !string.IsNullOrEmpty(view.scaleError);

            measureButton.SetLabel(failed ? LabelMeasureFailed
                : view.bodyScale > 0f ? $"×{view.bodyScale:0.00}" : LabelMeasure);
            measureButton.SetKind(failed ? UiButtonKind.TextBad
                : view.bodyScale > 0f ? UiButtonKind.TextGood : UiButtonKind.Normal);
            measureButton.SetInteractable(usable);
        }

        private void RefreshKickButton()
        {
            if (kickButton == null)
            {
                return;
            }

            bool armed = _kickArmedAt >= 0f;
            kickButton.SetLabel(armed ? LabelConfirm : "AT");
            kickButton.SetKind(armed ? UiButtonKind.Confirm : UiButtonKind.TextBad);
        }

        /// <summary>SIFIRLA look — same as <see cref="AdminStatsRow"/>: red lettering idle, the hold
        /// fill IS the progress bar, green SİLİNDİ after a wipe ("what you asked for happened").</summary>
        private void RefreshResetButton()
        {
            if (resetButton == null)
            {
                return;
            }

            // ⚠️ The RESULT outranks the press: the wipe lands at the threshold, so from that
            // moment the button says SİLİNDİ even though the finger is still down.
            bool purged = _purgedAt >= 0f;
            bool holding = !purged && _resetHold != null && _resetHold.IsPressed;
            _resetHoldPainted = holding || purged;

            resetButton.SetLabel(holding ? LabelPurging : purged ? LabelPurged : LabelReset);
            resetButton.SetKind(purged ? UiButtonKind.TextGood : UiButtonKind.TextBad);
            resetButton.SetHold(holding ? Mathf.Max(0.02f, _resetHold.HoldProgress) : 0f);
        }

        // ------------------------------------------- shared text tokens (stats panel)
        // ⚠️ These build the stats panel's single-line readout (AdminStatsRow), not the card: the
        // card shows the same facts as icons/ticks. Thresholds and glyphs stay HERE so the same
        // battery never differs between the two screens.

        /// <summary>Joins the non-empty tokens with the row separator.</summary>
        internal static string JoinTokens(params string[] tokens)
        {
            var line = new StringBuilder();
            foreach (string token in tokens)
            {
                if (string.IsNullOrEmpty(token))
                {
                    continue;
                }

                if (line.Length > 0)
                {
                    line.Append(" · ");
                }

                line.Append(token);
            }

            return line.ToString();
        }

        /// <summary>
        /// HEADSET battery text, rich-text coloured below the thresholds. <c>-</c> = unknown
        /// (<c>battery &lt; 0</c>) and stays uncoloured: alarming on an unknown value sends the
        /// operator running for nothing.
        /// </summary>
        internal static string FormatBattery(AdminPlayerView view)
        {
            if (view.battery < 0f)
            {
                return Unknown;
            }

            float level = Mathf.Clamp01(view.battery);
            string text = $"%{Mathf.RoundToInt(level * 100f)}";

            return level < BatteryCritical ? Colored(text, Girdap.Bad)
                : level < BatteryLow ? Colored(text, Girdap.Warn)
                : text;
        }

        /// <summary>
        /// Both controllers as one token (<c>K:</c> + two glyphs), each glyph coloured. Empty when
        /// neither hand is reported.
        /// </summary>
        internal static string FormatControllers(AdminPlayerView view)
        {
            if (view.ctrlL == ArenaProtocol.CONTROLLER_UNKNOWN &&
                view.ctrlR == ArenaProtocol.CONTROLLER_UNKNOWN)
            {
                return "";
            }

            return $"K:{ControllerGlyph(view.ctrlL)}{ControllerGlyph(view.ctrlR)}";
        }

        /// <summary>Body tracking as one token (<c>G:</c> + one glyph). Empty when unreported.</summary>
        internal static string FormatBody(AdminPlayerView view)
        {
            switch (view.body)
            {
                case ArenaProtocol.BODY_OK:
                    return "G:" + Colored(GlyphControllerOk, Girdap.Muted);
                case ArenaProtocol.BODY_FALLBACK:
                    return "G:" + Colored(GlyphBodyFallback, Girdap.Warn);
                case ArenaProtocol.BODY_NO_PERMISSION:
                    return "G:" + Colored(GlyphControllerLost, Girdap.Bad);
                default:
                    return "";
            }
        }

        private static string ControllerGlyph(int state)
        {
            switch (state)
            {
                case ArenaProtocol.CONTROLLER_OK:
                    return Colored(GlyphControllerOk, Girdap.Muted);
                case ArenaProtocol.CONTROLLER_UNTRACKED:
                    return Colored(GlyphControllerUntracked, Girdap.Warn);
                case ArenaProtocol.CONTROLLER_LOST:
                    return Colored(GlyphControllerLost, Girdap.Bad);
                default:
                    return Colored(GlyphControllerUnknown, Girdap.Faint);
            }
        }

        /// <summary>Colours one token with TMP rich text.
        /// <para>⚠️ Tag is <c>RGB</c>, not <c>RGBA</c>: TMP forces the coloured range fully opaque
        /// anyway, so a per-token alpha only risks invisible text.</para></summary>
        private static string Colored(string text, Color color)
        {
            return $"<color=#{ColorUtility.ToHtmlStringRGB(color)}>{text}</color>";
        }

#if UNITY_EDITOR
        /// <summary>
        /// Prefab wiring from <c>GirdapUiBuilder.BuildPlayerRow</c>.
        /// <para>⚠️ <b>Public, not internal:</b> the builder lives in another assembly
        /// (<c>VortexArena.App.Editor</c>) and there is no <c>InternalsVisibleTo</c>. Editor-only, so
        /// it ships in no player build.</para>
        /// </summary>
        public void EditorWire(UiShape card, Button select, CanvasGroup dim, UiShape plate,
            TextMeshProUGUI number, RectTransform top, TextMeshProUGUI playerName,
            TextMeshProUGUI id, UiChip chip, TextMeshProUGUI hpValue, UiSegmentBar bar,
            RectTransform tele, TextMeshProUGUI kdCaption, TextMeshProUGUI kdValue,
            Image battery, TextMeshProUGUI batteryValue, UiSegmentBar ctrlLeft,
            UiSegmentBar ctrlRight, Image body, UiButtonStyle pov, UiButtonStyle measure,
            UiButtonStyle team, UiButtonStyle reset, UiButtonStyle kick)
        {
            cardShape = card;
            selectButton = select;
            dimGroup = dim;
            numberPlate = plate;
            numberText = number;
            topRow = top;
            nameText = playerName;
            idText = id;
            statusChip = chip;
            hpText = hpValue;
            hpBar = bar;
            teleRow = tele;
            kdLabel = kdCaption;
            kdText = kdValue;
            batteryIcon = battery;
            batteryText = batteryValue;
            ctrlLeftDot = ctrlLeft;
            ctrlRightDot = ctrlRight;
            bodyIcon = body;
            povButton = pov;
            measureButton = measure;
            teamButton = team;
            resetButton = reset;
            kickButton = kick;
        }
#endif
    }
}
