using System;
using System.Collections.Generic;
using System.Text;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using VortexArena.Core;
using VortexArena.Core.UI;
using VortexArena.Net;
using VortexArena.Protocol;

namespace VortexArena.App.Admin
{
    /// <summary>
    /// The admin spectator's on-screen management UI — a <b>persistent</b> screen-space canvas that
    /// survives lobby ↔ arena transitions, so the operator never loses the interface.
    /// <para><b>Look comes from the prefab</b>
    /// (<c>Assets/_Shared/App/Resources/UI/AdminHud.prefab</c>, generated by
    /// <c>GirdapUiBuilder.Hud</c>); this class is behaviour only (data binding + refresh).
    /// <see cref="AdminSpectator"/> loads and instantiates it via <c>Resources.Load</c> — it is never
    /// placed in a scene, so adding an arena needs no setup step.</para>
    /// <para><b>sortingOrder = 4000</b> (on the prefab's Canvas): the connection error screen stays
    /// at 5000 and may cover the HUD — without a connection there is no live data to show. Changing
    /// it breaks the order of the two screens.</para>
    /// <para>Refresh is event driven (<see cref="AdminRoster.Changed"/>,
    /// <see cref="AdminSession.Changed"/>); only time-dependent fields (respawn countdown) tick at
    /// <see cref="RefreshInterval"/> (~4 Hz).</para>
    /// </summary>
    public class AdminHud : MonoBehaviour
    {
        /// <summary>Prefab path inside <c>Resources</c> (no extension).</summary>
        public const string ResourcePath = "UI/AdminHud";

        /// <summary>Refresh interval of time-dependent fields (s).</summary>
        private const float RefreshInterval = 0.25f;

        /// <summary>FIXED label of the chip under the scores. The chip is a button, so it says
        /// what it does — not the match phase.</summary>
        private const string ChipLabelText = "İSTATİSTİK";

        /// <summary><c>modeState</c> prefix of a round parked on its result (round-based modes, §10.1).</summary>
        private const string RoundEndPrefix = "roundend:";

        /// <summary>CSS <c>.col-head .t</c> padding — the team plate hugs its label.</summary>
        private const float PlatePadLeft = 14f;

        private const float PlatePadRight = 28f;

        /// <summary>CSS <c>.col-head { gap }</c> — team plate to player count.</summary>
        private const float HeadGap = 10f;

        /// <summary>CSS <c>.sb-clock</c> font size; the round-review notice gets the smaller one
        /// because it is a sentence, not a clock.</summary>
        private const float ClockFontSize = 48f;

        private const float ClockNoticeFontSize = 17f;

        [Header("Oyuncu satırı")]
        [Tooltip("Kolonlara örneklenecek satır prefabı (Resources/UI/AdminPlayerRow).")]
        [SerializeField] private AdminPlayerRow rowPrefab;

        [Tooltip("Kolon başına gösterilen en fazla satır; fazlası \"+N daha\" ile özetlenir.")]
        [SerializeField] private int maxRowsPerColumn = 5;

        [Tooltip("İki satır arasındaki boşluk (px).")]
        [SerializeField] private float rowGap = 8f;

        [Tooltip("Kolon başlığının yüksekliği (px) — ilk satır bunun altından başlar.")]
        [SerializeField] private float headerHeight = 38f;

        [Header("Skor bandı")]
        [SerializeField] private TextMeshProUGUI scoreRedText;
        [SerializeField] private TextMeshProUGUI scoreBlueText;
        [Tooltip("Üst banttaki maç saati. Koşan maçta geri sayar; maç yokken boştur.")]
        [SerializeField] private TextMeshProUGUI clockText;
        [Tooltip("Skor bandının altındaki chip: sabit \"İSTATİSTİK\" yazar, tıklanınca paneli açar.")]
        [SerializeField] private TextMeshProUGUI chipText;

        [Tooltip("FFA lider tablosu satırı. ⚠️ Girdap mockup'ında KARŞILIĞI YOK: yalnız metni " +
                 "varken görünür, takımlı maçta hiç çizilmez.")]
        [SerializeField] private TextMeshProUGUI leaderboardText;

        [Tooltip("Ko-op müşteri sayacı satırı (Mutlu/Mutsuz). Lider tablosu gibi mockup'ta " +
                 "karşılığı yoktur; yalnız metni varken görünür.")]
        [SerializeField] private TextMeshProUGUI customerCountsText;

        [Header("Kolonlar")]
        [Tooltip("Kırmızı takım kolonu; FFA'da tek kolon olarak kullanılır.")]
        [SerializeField] private RectTransform redColumn;
        [SerializeField] private RectTransform blueColumn;

        [Tooltip("Başlıktaki eğik takım plakası — rengi takımdan gelir, genişliği etikete göre ayarlanır.")]
        [SerializeField] private UiShape redTeamPlate;
        [SerializeField] private TextMeshProUGUI redTeamLabel;
        [Tooltip("Plakanın yanındaki \"N OYUNCU\" satırı.")]
        [SerializeField] private TextMeshProUGUI redHeader;
        [Tooltip("Başlığın sağ ucundaki \"N KALİBRESİZ\" rozeti; sıfırda gizlenir.")]
        [SerializeField] private UiChip redCalibChip;
        [Tooltip("Taşma kutusu (CSS .col-more) — gizlenip gösterilen kabuk.")]
        [SerializeField] private RectTransform redOverflowBox;
        [SerializeField] private TextMeshProUGUI redOverflow;

        [SerializeField] private UiShape blueTeamPlate;
        [SerializeField] private TextMeshProUGUI blueTeamLabel;
        [SerializeField] private TextMeshProUGUI blueHeader;
        [SerializeField] private UiChip blueCalibChip;
        [SerializeField] private RectTransform blueOverflowBox;
        [SerializeField] private TextMeshProUGUI blueOverflow;

        [Header("Kamera kipi (sağ üst)")]
        [Tooltip("Kamera kipi düğmeleri — sıra AdminCameraMode ile aynı: POV, SERBEST, KUŞ BAKIŞI. " +
                 "⚠️ POV yuvası (0) BOŞ bırakılır — POV'a oyuncu kartındaki düğmeden " +
                 "(HandleRowPov) ve klavyeden girilir; şeritte POV düğmesi yoktur. Dizi yine de " +
                 "enum indeksli kalır: kaydırmak SERBEST/KUŞ BAKIŞI'nı yanlış kipe bağlardı.")]
        [SerializeField] private UiButtonStyle[] modeButtons = new UiButtonStyle[3];

        [Header("Akışlar")]
        [SerializeField] private AdminKillFeedView killFeed;

        [Tooltip("İhlal akışı (§10.9) — kill feed'den AYRI olmalıdır: kill feed maçın hikâyesi, " +
                 "bu operatörün iş listesidir.")]
        [SerializeField] private AdminViolationFeedView violationFeed;

        [Header("Düğmeler")]
        [SerializeField] private Button preferencesButton;
        [SerializeField] private Button statsChipButton;

        private readonly List<AdminPlayerRow> _redRows = new List<AdminPlayerRow>();
        private readonly List<AdminPlayerRow> _blueRows = new List<AdminPlayerRow>();

        /// <summary>Sort buffer for the FFA leaderboard (avoids a list allocation per refresh).</summary>
        private readonly List<AdminPlayerView> _ranked = new List<AdminPlayerView>();

        private float _nextRefresh;
        private bool _dirty = true;
        private readonly StringBuilder _sb = new StringBuilder();
        private float _rowHeight = -1f;

        /// <summary>
        /// Row height read from the prefab so resizing the row reflows the column; falls back to
        /// the constant when the prefab is missing or its size is meaningless.
        /// </summary>
        private float RowHeight
        {
            get
            {
                if (_rowHeight > 1f)
                {
                    return _rowHeight;
                }

                float fromPrefab = rowPrefab != null
                    ? ((RectTransform)rowPrefab.transform).rect.height
                    : 0f;
                _rowHeight = fromPrefab > 1f ? fromPrefab : AdminPlayerRow.Height;
                return _rowHeight;
            }
        }

        private void Awake()
        {
            // ⚠ Arena scenes have NO EventSystem (only the lobby does) — guarantee one here, or the
            // HUD buttons die silently.
            UiKit.EnsureEventSystem();

            // Fallback only: the generated prefab carries the component with its bar references
            // wired. An added-at-runtime copy finds no references and draws no floor row.
            if (GetComponent<AdminFloorControls>() == null)
            {
                gameObject.AddComponent<AdminFloorControls>();
            }

            WireButtons();
        }

        /// <summary>
        /// Wires callbacks to the prefab's buttons. ⚠️ <b>No persistent <c>onClick</c> entries in
        /// the prefab:</b> the target is not static (selected player/panel state change) and an
        /// inspector-bound entry would skip the conditions applied here.
        /// </summary>
        private void WireButtons()
        {
            if (preferencesButton != null)
            {
                preferencesButton.onClick.RemoveAllListeners();
                preferencesButton.onClick.AddListener(() => AdminSession.TogglePanel(AdminPanelKind.Preferences));
            }

            if (statsChipButton != null)
            {
                statsChipButton.onClick.RemoveAllListeners();
                statsChipButton.onClick.AddListener(() => AdminSession.TogglePanel(AdminPanelKind.Stats));
            }

            for (int i = 0; i < modeButtons.Length; i++)
            {
                Button target = modeButtons[i] != null ? modeButtons[i].TargetButton : null;
                if (target == null)
                {
                    continue;
                }

                int index = i;
                target.onClick.RemoveAllListeners();
                target.onClick.AddListener(() => AdminSession.CameraMode = (AdminCameraMode)index);
            }
        }

        private void OnEnable()
        {
            AdminSession.Changed += MarkDirty;
            AdminSelection.Changed += MarkDirty; // another admin's action/selection
            NetEvents.OnConnectionStateChanged += HandleConnectionState;

            if (AdminRoster.Instance != null)
            {
                AdminRoster.Instance.Changed += MarkDirty;
            }
        }

        private void OnDisable()
        {
            AdminSession.Changed -= MarkDirty;
            AdminSelection.Changed -= MarkDirty;
            NetEvents.OnConnectionStateChanged -= HandleConnectionState;

            if (AdminRoster.Instance != null)
            {
                AdminRoster.Instance.Changed -= MarkDirty;
            }
        }

        private void Update()
        {
            bool tick = Time.unscaledTime >= _nextRefresh;
            if (tick)
            {
                _nextRefresh = Time.unscaledTime + RefreshInterval;
            }

            if (_dirty || tick)
            {
                _dirty = false;
                Refresh();
            }

            TickRows(_redRows);
            TickRows(_blueRows);
        }

        private void MarkDirty()
        {
            _dirty = true;
        }

        private void HandleConnectionState(ArenaConnectionState state)
        {
            _dirty = true;
        }

        // ---------------------------------------------------------------- tazeleme

        private void Refresh()
        {
            AdminRoster roster = AdminRoster.Instance;
            if (roster == null)
            {
                return;
            }

            RefreshTopBar(roster);
            RefreshColumns(roster);
            RefreshCameraBar();

            if (killFeed != null)
            {
                killFeed.Bind(roster.KillEvents, roster.KillFeedVersion);
            }

            if (violationFeed != null)
            {
                violationFeed.Bind(roster.ViolationEvents, roster.ViolationFeedVersion);
            }
        }

        private void RefreshTopBar(AdminRoster roster)
        {
            bool ffa = roster.IsFfa;
            // Co-op is teamless, so the team slots would both go blank — but it does have ONE score
            // the operator is watching. It takes the left slot; the right one stays empty because
            // there is no opponent to put there.
            bool sharedScore = ModeRuntime.IsCoop;

            if (scoreRedText != null)
            {
                scoreRedText.text = ffa && !sharedScore ? "" : roster.ScoreRed.ToString();
            }

            if (scoreBlueText != null)
            {
                scoreBlueText.text = ffa ? "" : roster.ScoreBlue.ToString();
            }

            // Co-op counters come from the same modeState line the stats panel reads (§10.1) — the
            // operator must not see a second set of numbers.
            bool coop = AdminModeState.TryCustomerCounts(roster.ModeState, out int happy, out int unhappy);
            string customerLine = coop ? $"Mutlu {happy} · Mutsuz {unhappy}" : "";

            SetOptionalLine(customerCountsText, customerLine);

            // Without a dedicated field the counters take the leaderboard slot: a co-op mode has no
            // leaderboard to hide, and the operator would otherwise have to open the stats panel.
            SetOptionalLine(leaderboardText, customerCountsText == null && coop
                ? customerLine
                : ffa ? LeaderboardLine(roster) : "");

            if (chipText != null)
            {
                // ⚠️ The chip is a BUTTON and says what it does — never the phase name. A varying
                // label made "where are the stats" a per-phase question.
                chipText.text = ChipLabelText;
            }

            if (clockText != null)
            {
                string line = ClockLine(roster);
                bool notice = line.Length > 5; // mm:ss is five characters; anything longer is a sentence

                clockText.text = line;
                clockText.fontSize = notice ? ClockNoticeFontSize : ClockFontSize;
                clockText.textWrappingMode =
                    notice ? TextWrappingModes.Normal : TextWrappingModes.NoWrap;
            }
        }

        /// <summary>
        /// An information line the Girdap mockup has no slot for: shown only while it HAS content, so
        /// a team match draws nothing where the design draws nothing — and FFA/co-op do not silently
        /// lose their only on-HUD numbers.
        /// </summary>
        private static void SetOptionalLine(TextMeshProUGUI target, string text)
        {
            if (target == null)
            {
                return;
            }

            target.text = text;
            bool show = !string.IsNullOrEmpty(text);
            if (target.gameObject.activeSelf != show)
            {
                target.gameObject.SetActive(show);
            }
        }

        /// <summary>The match clock on the top band, <c>mm:ss</c>. Empty in the lobby: a frozen 00:00
        /// over an empty arena reads as a stuck match.</summary>
        /// <remarks>What the number MEANS belongs to the mode (§10.1) — a round's remainder in a
        /// round-based match, the whole match's where that mode has no round limit. The panel only
        /// draws what <c>match_state</c> carries; it does not interpret it.
        /// <para>⚠️ One exception, and it is why the field is not purely a clock: on a round review the
        /// server is PARKED and the clock reads 00:00 with nothing to explain it. The wait ends by
        /// closing the stats panel (<c>mode_continue</c>), so the field names that key — an operator who
        /// never opened the panel has no other place to learn it.</para></remarks>
        private static string ClockLine(AdminRoster roster)
        {
            bool inLobby = roster.Phase == ArenaProtocol.PHASE_PAUSED &&
                           (string.IsNullOrEmpty(roster.PhaseReason) ||
                            roster.PhaseReason == ArenaProtocol.PAUSE_REASON_LOBBY);
            if (inLobby)
            {
                return "";
            }

            if (roster.Phase == ArenaProtocol.PHASE_PAUSED &&
                roster.PhaseReason == ArenaProtocol.PAUSE_REASON_MODE &&
                roster.ModeState.StartsWith(RoundEndPrefix, StringComparison.Ordinal))
            {
                return "TUR BİTTİ · I: TURA DEVAM";
            }

            int total = Mathf.Max(0, Mathf.CeilToInt(roster.TimeRemaining));
            return $"{total / 60:00}:{total % 60:00}";
        }

        /// <summary>
        /// FFA leaderboard: top 3 by score (<c>name · score</c>) — the only meaningful top-band
        /// content in a mode without team scores. Empty while nobody scored: a row of zeroes
        /// carries no information.
        /// </summary>
        private string LeaderboardLine(AdminRoster roster)
        {
            _ranked.Clear();
            for (int i = 0; i < roster.Players.Count; i++)
            {
                _ranked.Add(roster.Players[i]);
            }

            if (_ranked.Count == 0)
            {
                return "";
            }

            _ranked.Sort(CompareByScoreDescending);
            if (_ranked[0].score <= 0)
            {
                return "";
            }

            _sb.Clear();
            int shown = Mathf.Min(3, _ranked.Count);
            for (int i = 0; i < shown; i++)
            {
                if (i > 0)
                {
                    _sb.Append("   ");
                }

                _sb.Append($"{i + 1}. {_ranked[i].name} {_ranked[i].score}");
            }

            return _sb.ToString();
        }

        private static int CompareByScoreDescending(AdminPlayerView a, AdminPlayerView b)
        {
            int byScore = b.score.CompareTo(a.score);
            return byScore != 0 ? byScore : a.playerId.CompareTo(b.playerId);
        }

        private void RefreshColumns(AdminRoster roster)
        {
            if (roster.IsFfa)
            {
                // One column: the plate loses its team color, so it says what the list IS.
                BindHeader(redTeamPlate, redTeamLabel, redHeader, redCalibChip, "OYUNCULAR", "",
                    roster.Players);
                BindColumn(_redRows, redColumn, redOverflowBox, redOverflow, roster.Players);

                BindHeader(blueTeamPlate, blueTeamLabel, blueHeader, blueCalibChip, "", "", null);
                BindColumn(_blueRows, blueColumn, blueOverflowBox, blueOverflow, null);
                return;
            }

            BindHeader(redTeamPlate, redTeamLabel, redHeader, redCalibChip, "KIRMIZI", "red",
                roster.Red);
            BindColumn(_redRows, redColumn, redOverflowBox, redOverflow, roster.Red);

            BindHeader(blueTeamPlate, blueTeamLabel, blueHeader, blueCalibChip, "MAVİ", "blue",
                roster.Blue);
            BindColumn(_blueRows, blueColumn, blueOverflowBox, blueOverflow, roster.Blue);
        }

        /// <summary>
        /// Column header: slanted team plate + player count + calibration badge (CSS
        /// <c>.col-head</c>). The plate is measured and resized here — "OYUNCULAR" and "MAVİ" are not
        /// the same width, and a fixed plate would either clip or leave a gap.
        /// </summary>
        private void BindHeader(UiShape plate, TextMeshProUGUI plateLabel, TextMeshProUGUI count,
            UiChip calibration, string title, string team, IReadOnlyList<AdminPlayerView> players)
        {
            bool shown = !string.IsNullOrEmpty(title);
            float plateWidth = 0f;

            if (plateLabel != null)
            {
                plateLabel.text = title;
                float textWidth = shown ? Mathf.Ceil(plateLabel.GetPreferredValues(title).x) : 0f;
                plateWidth = PlatePadLeft + textWidth + PlatePadRight;
                plateLabel.rectTransform.sizeDelta = new Vector2(textWidth, headerHeight);
            }

            if (plate != null)
            {
                plate.gameObject.SetActive(shown);
                plate.rectTransform.sizeDelta = new Vector2(plateWidth, headerHeight);
                plate.Fill(Girdap.TeamHi(team), Girdap.TeamLo(team), UiGradientMode.Vertical);
            }

            if (count != null)
            {
                int total = players != null ? players.Count : 0;
                count.text = shown ? $"{total} OYUNCU" : "";
                count.rectTransform.anchoredPosition = new Vector2(plateWidth + HeadGap, 0f);
            }

            if (calibration == null)
            {
                return;
            }

            // Nothing is drawn at zero (§10.6) — a permanent "0 uncalibrated" is noise.
            int needs = CalibrationCount(players);
            calibration.gameObject.SetActive(needs > 0);
            if (needs > 0)
            {
                calibration.Set($"{needs} KALİBRESİZ", UiChipKind.Warn, "Warn");
            }
        }

        /// <summary>How many rows in the column need operator attention (§10.6).</summary>
        private static int CalibrationCount(IReadOnlyList<AdminPlayerView> players)
        {
            if (players == null)
            {
                return 0;
            }

            int count = 0;
            for (int i = 0; i < players.Count; i++)
            {
                if (players[i] != null && players[i].NeedsCalibration)
                {
                    count++;
                }
            }

            return count;
        }

        private void BindColumn(List<AdminPlayerRow> rows, RectTransform column,
            RectTransform overflowBox, TextMeshProUGUI overflow,
            IReadOnlyList<AdminPlayerView> players)
        {
            if (column == null)
            {
                return;
            }

            int count = players != null ? Mathf.Min(players.Count, maxRowsPerColumn) : 0;

            while (rows.Count < count)
            {
                if (rowPrefab == null)
                {
                    Debug.LogWarning("[AdminHud] rowPrefab atanmadı; oyuncu satırları çizilemiyor.");
                    break;
                }

                AdminPlayerRow row = Instantiate(rowPrefab, column);
                row.Initialize(HandleRowSelected, HandleRowPov);
                rows.Add(row);
            }

            // CSS `.col { gap: 8 }` sits between the header and the first card too.
            float top = headerHeight + rowGap;
            float height = RowHeight;
            for (int i = 0; i < rows.Count; i++)
            {
                if (i >= count)
                {
                    rows[i].SetVisible(false);
                    continue;
                }

                rows[i].SetVisible(true);
                rows[i].Place(top + i * (height + rowGap), height);
                rows[i].Bind(players[i], players[i].playerId == AdminSession.SelectedPlayerId);
            }

            int hidden = players != null ? players.Count - count : 0;
            if (overflow != null)
            {
                overflow.text = hidden > 0 ? $"+{hidden} oyuncu daha (istatistiklerde)" : "";
            }

            if (overflowBox == null)
            {
                return;
            }

            overflowBox.gameObject.SetActive(hidden > 0);
            if (hidden > 0)
            {
                overflowBox.anchoredPosition =
                    new Vector2(overflowBox.anchoredPosition.x, -(top + count * (height + rowGap)));
            }
        }

        /// <summary>Lights the active camera mode button. ⚠️ Slot 0 (POV) is empty — that mode is
        /// entered only from a player card or the keyboard, so in POV neither segment is lit, which is
        /// exactly what the mockup shows.</summary>
        private void RefreshCameraBar()
        {
            var active = (int)AdminSession.CameraMode;
            for (int i = 0; i < modeButtons.Length; i++)
            {
                if (modeButtons[i] != null)
                {
                    modeButtons[i].SetKind(i == active ? UiButtonKind.SegOn : UiButtonKind.Seg);
                }
            }
        }

        private static void TickRows(List<AdminPlayerRow> rows)
        {
            for (int i = 0; i < rows.Count; i++)
            {
                rows[i].Tick();
            }
        }

        // ------------------------------------------------------------- callbacks

        private void HandleRowSelected(int playerId)
        {
            AdminSession.SelectedPlayerId = playerId;
        }

        private void HandleRowPov(int playerId)
        {
            AdminSession.SelectedPlayerId = playerId;
            AdminSession.CameraMode = AdminCameraMode.Pov;
        }
    }
}
