using System;
using TMPro;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.InputSystem;
using UnityEngine.UI;
using VortexArena.Core;
using VortexArena.Core.UI;
using VortexArena.Protocol;

namespace VortexArena.App.Admin
{
    /// <summary>
    /// Single player row of the stats table: number plate, name + <c>#id</c>, state chip, the
    /// K/D/KD/score cells, telemetry cells (battery · controllers · body · floor · ping), the
    /// violation ledger and the action strip (KALİBRE · ÖLÇ · rename · SIFIRLA · AT).
    /// <para>
    /// <b>Why a sibling of <see cref="AdminPlayerRow"/> but a separate class:</b> the side card is
    /// narrow and belongs to scene control (POV/team/identity); this row is wide, table-like
    /// and belongs to the operator's <i>record keeping</i> screen. Merging them means a "which
    /// screen am I on" branch in every <c>Bind</c>, where a fix for one screen silently breaks the
    /// other.
    /// </para>
    /// <para>
    /// <b>Look comes from the prefab</b> (<c>Assets/_Shared/App/Resources/UI/</c>, generated by
    /// <c>GirdapUiBuilder</c>); this class is behaviour only. Unbound prefab fields silently draw
    /// nothing.
    /// </para>
    /// <para>
    /// ⚠️ <b>ONE row prefab, one table.</b> There is no narrow/icon variant: the panel draws every
    /// player in a single full-width table with a group row per team. Do not fork a second prefab —
    /// the cell x positions are the table's column grid and a second copy drifts away from it.
    /// </para>
    /// <para>
    /// ⚠️ <b>HP is absent by DESIGN</b> — it lives on the side panel card as a bar. Violations
    /// appear here as a <b>ledger</b> (count per kind) and deliberately do not blink: the live
    /// channel is the HUD strip and the card border.
    /// </para>
    /// <para>
    /// ⚠️ <b>SIFIRLA is ONE button carrying BOTH reset modes</b> (<see cref="HoldButton"/>): a tap
    /// voids the current alignment and keeps the headset's saved anchor, a 1 s hold wipes that
    /// anchor too — afterwards KALİBRE fails and the player must redo the A/B sequence by hand.
    /// Severity comes from press DURATION, never from picking the right neighbour: two separate
    /// buttons made the operator choose a severity before knowing they needed one, and put the
    /// destructive one a mis-click away. The side card (<see cref="AdminPlayerRow"/>) carries no
    /// calibration button; this row is the only place.
    /// </para>
    /// <para>
    /// ⚠️ <b>KALİBRE is the OPPOSITE action and stays its own button:</b> it <i>reloads</i>
    /// alignment from the saved anchor and destroys nothing. The two sit at opposite ends of the
    /// button strip so a mis-aimed click cannot land on the other.
    /// </para>
    /// </summary>
    public class AdminStatsRow : MonoBehaviour
    {
        /// <summary>Row height <b>fallback</b> (px, CSS <c>.trow</c>); real height is read from the
        /// prefab's <see cref="RectTransform"/> (<see cref="AdminStatsPanel"/>) so resizing it in
        /// the prefab reflows the list.</summary>
        public const float Height = 44f;

        /// <summary>Confirm window (s) of the AT button — same as <see cref="AdminPlayerRow"/>.
        /// ⚠️ SIFIRLA does NOT use it: its friction is the hold (<see cref="HoldButton"/>).</summary>
        private const float ConfirmSeconds = 3f;

        /// <summary>How long the result label ("TAMAM"/"HATA") stays up (s). Permanent would show
        /// a stale result until the next attempt.</summary>
        private const float ResultHoldSeconds = 2f;

        /// <summary>
        /// Longest wait for a reload reply (s).
        /// <para>⚠️ <b>Required:</b> if the headset is closed or frozen <c>calibration_result</c>
        /// never arrives and the button would hang on "YÜKLENİYOR" forever — no result, no retry.</para>
        /// <para>⚠️ Kept clearly LONGER than the headset's own retry window
        /// (<c>ArenaCalibrator.RestoreAttempts</c> × <c>RestoreRetryDelayMs</c> ≈ 10 s, plus each
        /// attempt's load/localize wait): too short and the button says "no reply" seconds before
        /// the real result, making the operator read a success as a failure. If that window grows,
        /// this one grows too.</para>
        /// </summary>
        private const float LoadTimeoutSeconds = 25f;

        /// <summary>Headset battery warning thresholds (0..1). ⚠️ Same numbers as
        /// <see cref="AdminPlayerRow"/>: the same battery must not be red on one screen and yellow
        /// on the other.</summary>
        private const float BatteryCritical = 0.25f;

        /// <inheritdoc cref="BatteryCritical"/>
        private const float BatteryLow = 0.5f;

        // ⚠️ No symbols/emoji in labels: TMP's default font does not guarantee them and a missing
        // glyph draws □ (same rule as AdminPlayerRow). Colour + "!" carry the state.
        private const string LabelConfirm = "EMİN?";
        private const string LabelKick = "AT";
        private const string LabelReset = "SIFIRLA";

        /// <summary>SIFIRLA while the hard-reset hold is running. ⚠️ Names what is being DESTROYED,
        /// not "keep holding": the operator must be able to abort by reading the button.</summary>
        private const string LabelPurging = "SİLİNİYOR";

        /// <summary>Confirmation shown right after the device record is wiped.
        /// ⚠️ <b>Required:</b> the hold has no other ending — without it the button snaps back to
        /// SIFIRLA and a completed wipe reads exactly like one aborted by sliding off.</summary>
        private const string LabelPurged = "SİLİNDİ";
        private const string LabelMeasure = "ÖLÇ";

        /// <summary>⚠️ Short, not "ÖLÇÜLEMEDİ": the cell is 48 px wide (table column grid) and the
        /// long word would run over its neighbours.</summary>
        private const string LabelMeasureFailed = "HATA";
        private const string LabelCalibrate = "KALİBRE";
        private const string LabelCalibrateUncalibrated = "KALİBRE !";
        private const string LabelCalibrateLoading = "YÜKLENİYOR";
        private const string LabelCalibrateOk = "TAMAM";
        private const string LabelCalibrateFailed = "HATA";

        /// <summary>Reason shown when no reply ever arrives — a bare "HATA" without a cause would
        /// leave the operator guessing.</summary>
        private const string TimeoutReason = "başlıktan yanıt gelmedi";

        /// <summary>Empty-cell mark (floor · ping · violation ledger). ⚠️ Written out: an empty cell
        /// cannot be told apart from a cell that was never drawn.</summary>
        private const string EmptyCell = "—";

        private const float DeadColorScale = 0.5f;

        /// <summary>Row dimming (CSS <c>.trow.away</c>, same grades as
        /// <see cref="AdminPlayerRow"/>): a device expected back must not look like one removed
        /// from the game.</summary>
        private const float ReconnectingAlpha = 0.7f;

        /// <inheritdoc cref="ReconnectingAlpha"/>
        private const float LeftAlpha = 0.5f;

        /// <summary>"Not reported" hand glyph. ⚠️ Not <see cref="Girdap.Faint"/>: unknown must read
        /// as "no data", not as a dim but valid state.</summary>
        private static readonly Color CtrlUnknown = Girdap.CtrlUnknown;

        /// <summary>KALİBRE button state — drives its label and interactability.</summary>
        private enum LoadState
        {
            Idle,
            Loading,
            Ok,
            Failed
        }

        [Header("Satır")]
        [Tooltip("Satır zemini; seçim vurgusu bunun kenarlığıyla verilir.")]
        [SerializeField] private UiShape rowShape;
        [Tooltip("Satırı seçen düğme — zeminin üstündedir.")]
        [SerializeField] private Button selectButton;
        [Tooltip("Soldaki takım renkli forma numarası plakası.")]
        [SerializeField] private UiShape numberPlate;
        [SerializeField] private TextMeshProUGUI numberText;

        [Header("Kimlik")]
        [SerializeField] private TextMeshProUGUI nameText;
        [SerializeField] private TextMeshProUGUI idText;
        [Tooltip("Düzenleme kipinde açılan grup (giriş alanı + onay/iptal). Kapalıyken ad okunur.")]
        [SerializeField] private GameObject nameEditRoot;
        [SerializeField] private TMP_InputField nameInput;
        [SerializeField] private Button nameApplyButton;
        [SerializeField] private Button nameCancelButton;

        [Header("Durum")]
        [Tooltip("DURUM hücresi: hazır/bekliyor/ölü… ya da kalibrasyon yoksa KALİBRESİZ.")]
        [SerializeField] private UiChip stateChip;

        [Header("Sayı hücreleri")]
        [SerializeField] private TextMeshProUGUI killsText;
        [SerializeField] private TextMeshProUGUI deathsText;
        [SerializeField] private TextMeshProUGUI kdText;
        [SerializeField] private TextMeshProUGUI scoreText;

        [Header("Telemetri hücreleri")]
        [SerializeField] private Image batteryIcon;
        [SerializeField] private TextMeshProUGUI batteryText;
        [Tooltip("İki kumandanın eğik çubukları (sol · sağ); rengi durumu taşır.")]
        [SerializeField] private UiShape ctrlLeftBar;
        [SerializeField] private UiShape ctrlRightBar;
        [SerializeField] private Image bodyIcon;
        [SerializeField] private TextMeshProUGUI floorText;
        [SerializeField] private TextMeshProUGUI pingText;

        [Header("İhlal defteri")]
        [SerializeField] private UiChip obstacleChip;
        [SerializeField] private UiChip outOfBoundsChip;
        [Tooltip("Son kalibrasyon yükleme hatası — ihlal hücresinin sonunda kalır (§10.6).")]
        [SerializeField] private UiChip calibrationErrorChip;
        [Tooltip("İhlal yoksa yazılan tire; rozetler gizlenir.")]
        [SerializeField] private TextMeshProUGUI violationEmpty;

        [Header("Eylem düğmeleri")]
        [Tooltip("Gözlükteki KAYITLI çapa verisinden kalibrasyonu yeniden yükletir (sıfırlamaz).")]
        [SerializeField] private UiButtonStyle calibrateButton;
        [Tooltip("Gövde ölçüsünü aldırır (§10.8). Etiketi aynı zamanda GÖSTERGEDİR.")]
        [SerializeField] private UiButtonStyle measureButton;
        [Tooltip("Satırı ad düzenleme kipine alır (kalem).")]
        [SerializeField] private UiButtonStyle renameButton;
        [Tooltip("Kalibrasyonu sıfırlar — TEK düğme: kısa basış o anki hizalamayı düşürür, " +
                 "1 sn basılı tutmak gözlükteki KAYITLI çapayı da sildirir (ardından KALİBRE iş " +
                 "görmez, oyuncu elle A/B almak zorunda kalır).")]
        [SerializeField] private UiButtonStyle resetButton;
        [Tooltip("Oyuncuyu maçtan atar — iki adımlı onay.")]
        [SerializeField] private UiButtonStyle kickButton;

        private RectTransform _rect;
        private Action<int> _onSelect;
        private Action<int, string> _onPopup;

        private int _playerId;
        private bool _calibrated = true;
        private bool _hasLeft;
        private float _floorOffset;
        private float _kickArmedAt = -1f;

        /// <summary>Press-duration gate of SIFIRLA; null when the button is unwired.</summary>
        private HoldButton _resetHold;

        /// <summary>Was SIFIRLA painted in its "holding" look last frame — without it the button
        /// would stay red after the press ends (<see cref="Tick"/> repaints only while pressed).</summary>
        private bool _resetHoldPainted;

        /// <summary>When the device record was wiped (<c>Time.unscaledTime</c>); &lt; 0 = no
        /// confirmation showing. Held for <see cref="ResultHoldSeconds"/>, like TAMAM/HATA.</summary>
        private float _purgedAt = -1f;

        /// <summary>Name edit mode. While on, <see cref="Bind"/> leaves the name alone — hence a
        /// field rather than a local.</summary>
        private bool _editing;

        private LoadState _loadState = LoadState.Idle;

        /// <summary>When the load/result state was entered (<c>Time.unscaledTime</c>); timeout and
        /// result hold are measured from it.</summary>
        private float _loadStateAt = -1f;

        public int PlayerId => _playerId;

        private RectTransform Rect => _rect != null ? _rect : _rect = (RectTransform)transform;

        /// <summary>
        /// Wires button callbacks. ⚠️ No <c>onClick</c> entries in the prefab: the target player
        /// changes on every <see cref="Bind"/>, so a persistent entry would command the wrong one.
        /// </summary>
        /// <param name="onSelect">Row selected (panel updates the selected player).</param>
        /// <param name="onPopup">Calibration reload failed — the panel shows the reason.</param>
        public void Initialize(Action<int> onSelect, Action<int, string> onPopup)
        {
            _onSelect = onSelect;
            _onPopup = onPopup;

            Wire(selectButton, () => _onSelect?.Invoke(_playerId));
            Wire(ButtonOf(renameButton), BeginNameEdit);
            Wire(nameApplyButton, ApplyNameEdit);
            Wire(nameCancelButton, CancelNameEdit);
            Wire(ButtonOf(kickButton), PressKick);
            // ⚠️ NOT Wire(): onClick fires on pointer-up whatever the duration, so a completed hold
            // would also send the soft reset — the player would be reset twice.
            _resetHold = HoldButton.Attach(ButtonOf(resetButton), PressReset, PressPurge);
            // ⚠️ One step (no confirm): measuring is undoable — a stray press is fixed by measuring
            // again (same reason as AdminPlayerRow).
            Wire(ButtonOf(measureButton), () => AdminCommands.MeasureBodyScale(_playerId));
            Wire(ButtonOf(calibrateButton), PressCalibrate);

            if (nameInput != null)
            {
                // Enter = apply: the operator should not have to reach for the mouse mid-edit.
                nameInput.onSubmit.RemoveAllListeners();
                nameInput.onSubmit.AddListener(_ => ApplyNameEdit());
            }

            SetNameEditActive(false);
            RefreshKickButton();
            RefreshResetButton();
            RefreshCalibrateButton();
        }

        private static Button ButtonOf(UiButtonStyle style)
        {
            return style != null ? style.TargetButton : null;
        }

        private static void Wire(Button button, UnityAction action)
        {
            if (button == null)
            {
                return;
            }

            button.onClick.RemoveAllListeners();
            button.onClick.AddListener(action);
        }

        private static void SetCellActive(Component cell, bool active)
        {
            if (cell != null && cell.gameObject.activeSelf != active)
            {
                cell.gameObject.SetActive(active);
            }
        }

        /// <summary>Binds the row to a player (called on every refresh).</summary>
        public void Bind(AdminPlayerView view, bool selected)
        {
            if (view == null)
            {
                return;
            }

            // ⚠️ Open modes are CLOSED when the row rebinds to another player: a kept edit mode
            // would send one player's typed name to another, and a pending load would show the
            // previous player's result here.
            if (_playerId != view.playerId)
            {
                SetNameEditActive(false);
                _kickArmedAt = -1f;
                _resetHold?.Cancel();
                _purgedAt = -1f;
                SetLoadState(LoadState.Idle);
            }

            _playerId = view.playerId;
            _calibrated = view.calibrated;
            _hasLeft = view.HasLeft;
            _floorOffset = view.floorOffset;

            // Graded dimming: connected 1.0, expected back 0.7, left 0.5 — "may return" and "gone"
            // are two different operator decisions.
            float alpha = view.IsConnected ? 1f : view.IsReconnecting ? ReconnectingAlpha : LeftAlpha;

            ApplyRowSurface(view, selected, alpha);
            ApplyIdentity(view, alpha);
            ApplyStateChip(view, alpha);
            ApplyCounters(view, alpha);
            ApplyTelemetry(view, alpha);
            ApplyViolations(view, alpha);

            // A left row has no command target (§10.2): the player is out, the row only carries
            // match stats. A dead button would feel like "sent but nothing happened".
            SetInteractable(kickButton, !view.HasLeft);
            SetInteractable(renameButton, !view.HasLeft);
            // ⚠️ Purging needs the headset ONLINE: the server only forwards the command to a live
            // connection, so on a left row it would look sent and delete nothing.
            SetInteractable(resetButton, !view.HasLeft);

            RefreshMeasureButton(view);
            RefreshKickButton();
            RefreshResetButton();
            RefreshCalibrateButton();
        }

        /// <summary>Expires the confirm window, load timeout and result hold (panel calls every
        /// frame).</summary>
        public void Tick()
        {
            if (_kickArmedAt >= 0f && Time.unscaledTime - _kickArmedAt > ConfirmSeconds)
            {
                _kickArmedAt = -1f;
                RefreshKickButton();
            }

            if (_resetHold != null && (_resetHold.IsPressed || _resetHoldPainted))
            {
                RefreshResetButton();
            }

            if (_purgedAt >= 0f)
            {
                // ⚠️ The window starts when the FINGER LIFTS — see AdminPlayerRow.Tick for why.
                if (_resetHold != null && _resetHold.IsPressed)
                {
                    _purgedAt = Time.unscaledTime;
                }
                else if (Time.unscaledTime - _purgedAt > ResultHoldSeconds)
                {
                    _purgedAt = -1f;
                    RefreshResetButton();
                }
            }

            if (_loadState == LoadState.Loading &&
                Time.unscaledTime - _loadStateAt > LoadTimeoutSeconds)
            {
                // No reply at all is treated as a failure: dropping it silently would read as
                // "the command went through".
                ApplyCalibrationResult(false, TimeoutReason);
                return;
            }

            if ((_loadState == LoadState.Ok || _loadState == LoadState.Failed) &&
                Time.unscaledTime - _loadStateAt > ResultHoldSeconds)
            {
                SetLoadState(LoadState.Idle);
            }
        }

        public void SetVisible(bool visible)
        {
            if (gameObject.activeSelf == visible)
            {
                return;
            }

            if (!visible)
            {
                // ⚠️ Never leave edit mode on a hidden row: after a relayout the same row lands on
                // another player and the typed name would go to them.
                SetNameEditActive(false);

                // ⚠️ Half-armed confirms die with the row too: a hidden row gets no Tick (the panel
                // only ticks visible ones), so an armed window would survive the hide and fire the
                // destructive command on the FIRST click after the row comes back.
                _kickArmedAt = -1f;
                _resetHold?.Cancel();
                _purgedAt = -1f;
                RefreshKickButton();
                RefreshResetButton();
            }

            gameObject.SetActive(visible);
        }

        /// <summary>Places the row at the given top offset inside the list; it spans the list's full
        /// width (the cell x positions ARE the table's column grid).</summary>
        public void Place(float top, float height)
        {
            RectTransform rect = Rect;
            rect.anchorMin = new Vector2(0f, 1f);
            rect.anchorMax = new Vector2(1f, 1f);
            rect.pivot = new Vector2(0.5f, 1f);
            rect.offsetMin = new Vector2(0f, -(top + height));
            rect.offsetMax = new Vector2(0f, -top);
        }

        /// <summary>
        /// Puts the button into "loading". The <b>bulk action</b> (TÜMÜNÜ KALİBRE ET) calls this
        /// BEFORE sending: if the command returned its result immediately, the row would not be in
        /// loading state yet and the result would be swallowed unseen.
        /// </summary>
        public void BeginCalibrationLoad()
        {
            SetLoadState(LoadState.Loading);
        }

        /// <summary>
        /// Result of a reload attempt (§5.3 <c>calibration_result</c> or timeout).
        /// <para>No popup on success — the "TAMAM" state is enough; on failure the reason goes to
        /// the panel's toast, since a narrow button cannot carry more than "HATA".</para>
        /// </summary>
        public void ApplyCalibrationResult(bool ok, string error)
        {
            SetLoadState(ok ? LoadState.Ok : LoadState.Failed);

            if (!ok)
            {
                _onPopup?.Invoke(_playerId,
                    string.IsNullOrEmpty(error) ? "kalibrasyon yüklenemedi" : error);
            }
        }

        // ------------------------------------------------------------------- cells

        private void ApplyRowSurface(AdminPlayerView view, bool selected, float alpha)
        {
            if (rowShape != null)
            {
                // Selection is the ONLY row-level border state here: an uncalibrated row is marked
                // by its state chip and its KALİBRE button, so a third red channel would compete
                // with the selection the operator just made.
                rowShape.Outline(selected ? 1f : 0f, Girdap.Acc);
            }

            if (numberPlate != null)
            {
                string team = view.team;
                Color hi = Girdap.TeamHi(team);
                Color lo = Girdap.TeamLo(team);
                if (!view.alive)
                {
                    hi = Dim(hi, DeadColorScale);
                    lo = Dim(lo, DeadColorScale);
                }

                numberPlate.Fill(Fade(hi, alpha), Fade(lo, alpha), UiGradientMode.Vertical);
            }

            if (numberText != null)
            {
                // 0 = unassigned (admins): the plate stays but carries no number.
                numberText.text = view.number > 0 ? view.number.ToString() : "";
                numberText.color = Fade(Color.white, alpha);
            }
        }

        private void ApplyIdentity(AdminPlayerView view, float alpha)
        {
            if (nameText != null && !_editing)
            {
                // ⚠️ Never touch the name while editing: the roster refreshes several times a
                // second and would silently overwrite what the operator typed.
                // The number is its own cell, so the name cell carries the name alone.
                nameText.text = view.name;
                nameText.color = Fade(view.alive ? Girdap.Text : Girdap.Faint, alpha);
            }

            if (idText != null)
            {
                idText.text = $"#{view.playerId}";
                idText.color = Fade(Girdap.Faint, alpha);
            }
        }

        /// <summary>DURUM cell. ⚠️ An uncalibrated headset OUTRANKS the play state: until it is
        /// fixed the player cannot take part, so "hazır" there would be a lie.</summary>
        private void ApplyStateChip(AdminPlayerView view, float alpha)
        {
            if (stateChip == null)
            {
                return;
            }

            // Uncalibrated is NOT a state here: the KALİBRE button already turns warn for it, and
            // the chip keeps saying what the player is doing (mockup `.trow`).
            stateChip.Set(StateText(view), StateChipKind(view));

            if (stateChip.Label != null)
            {
                stateChip.Label.color = Fade(stateChip.Label.color, alpha);
            }
        }

        private static UiChipKind StateChipKind(AdminPlayerView view)
        {
            if (!view.alive)
            {
                return UiChipKind.Dead;
            }

            // Away rows get the chip's base SURFACE (CSS plain `.chip`), not the surfaceless
            // variant: "yeniden bağlanıyor (12 sn)" is a standing condition, and a bare label in a
            // dimmed row reads as a leftover rather than a state.
            if (!view.IsConnected)
            {
                return UiChipKind.Neutral;
            }

            return view.ready ? UiChipKind.Good : UiChipKind.Plain;
        }

        private void ApplyCounters(AdminPlayerView view, float alpha)
        {
            // No weapon or no opponent → the three cells can only print zeros; they are hidden rather
            // than zeroed so the row does not teach the operator to ignore numbers.
            // ⚠️ Written on every Bind, not only switched off: rows are pooled and survive the match.
            bool combat = !ModeRuntime.HidesCombatStats;
            SetCellActive(killsText, combat);
            SetCellActive(deathsText, combat);
            SetCellActive(kdText, combat);

            Color number = Fade(view.IsConnected ? Girdap.Text : Girdap.Faint, alpha);

            if (killsText != null)
            {
                killsText.text = view.kills.ToString();
                killsText.color = number;
            }

            if (deathsText != null)
            {
                deathsText.text = view.deaths.ToString();
                deathsText.color = number;
            }

            if (kdText != null)
            {
                // The ratio is undefined without deaths; printing the kill count in the same format
                // gives a readable value instead of a division by zero.
                kdText.text = view.deaths > 0
                    ? (view.kills / (float)view.deaths).ToString("0.00")
                    : view.kills.ToString("0.00");
                kdText.color = number;
            }

            if (scoreText != null)
            {
                scoreText.text = view.score.ToString();
                scoreText.color = number;
            }
        }

        private void ApplyTelemetry(AdminPlayerView view, float alpha)
        {
            ApplyBattery(view, alpha);
            ApplyController(ctrlLeftBar, view.ctrlL, alpha);
            ApplyController(ctrlRightBar, view.ctrlR, alpha);

            if (bodyIcon != null)
            {
                bodyIcon.color = Fade(BodyColor(view.body), alpha);
            }

            if (floorText != null)
            {
                // Ground floor is the norm, so it is NOT written out: a "0. kat" on every row of
                // every single-floor arena would be noise the operator learns to skip.
                floorText.text = view.floor > 0 ? $"{view.floor}. kat" : EmptyCell;
                floorText.color = Fade(Girdap.Muted, alpha);
            }

            if (pingText != null)
            {
                // §6.7: -1 = no measurement. The dash must not read as "0 ms ping".
                pingText.text = view.rttMs < 0 ? EmptyCell : $"{view.rttMs} ms";
                pingText.color = Fade(Girdap.Muted, alpha);
            }
        }

        private void ApplyBattery(AdminPlayerView view, float alpha)
        {
            bool known = view.battery >= 0f;
            float level = Mathf.Clamp01(view.battery);

            // Unknown stays uncoloured: alarming on a value nobody reported sends the operator
            // running for nothing.
            Color color = !known ? Girdap.Muted
                : level < BatteryCritical ? Girdap.Bad
                : level < BatteryLow ? Girdap.Warn
                : Girdap.Muted;

            if (batteryText != null)
            {
                batteryText.text = known ? $"%{Mathf.RoundToInt(level * 100f)}" : EmptyCell;
                batteryText.color = Fade(color, alpha);
            }

            if (batteryIcon != null)
            {
                batteryIcon.color = Fade(color, alpha);
            }
        }

        /// <summary>
        /// One controller hand as a coloured bar.
        /// <para>⚠️ No percentage possible: controller charge is unreadable under OpenXR on Quest
        /// (§5.1). The actionable fact is "did this hand drop".</para>
        /// </summary>
        private static void ApplyController(UiShape bar, int state, float alpha)
        {
            if (bar == null)
            {
                return;
            }

            Color color;
            switch (state)
            {
                case ArenaProtocol.CONTROLLER_OK:
                    color = Girdap.Muted;
                    break;
                case ArenaProtocol.CONTROLLER_UNTRACKED:
                    color = Girdap.Warn;
                    break;
                case ArenaProtocol.CONTROLLER_LOST:
                    color = Girdap.Bad;
                    break;
                default:
                    color = CtrlUnknown;
                    break;
            }

            bar.Fill(Fade(color, alpha));
        }

        /// <summary>
        /// Body tracking colour.
        /// <para>⚠️ The fault has NO local trace: the player's own screen looks normal, the T-pose
        /// shows only on other screens (§5.1). This cell is the operator's only readout.</para>
        /// </summary>
        private static Color BodyColor(int state)
        {
            switch (state)
            {
                case ArenaProtocol.BODY_OK:
                    return Girdap.Muted;
                case ArenaProtocol.BODY_FALLBACK:
                    return Girdap.Warn;
                case ArenaProtocol.BODY_NO_PERMISSION:
                    return Girdap.Bad;
                default:
                    return CtrlUnknown;
            }
        }

        /// <summary>
        /// Violation ledger cell: one chip per kind, then the last calibration failure.
        /// <para>⚠️ <b>No blinking, no "ongoing" mark</b> — this is the ledger; the live channel is
        /// the HUD strip and the card border.</para>
        /// <para>⚠️ The last reload failure reason STAYS here (§10.6): the toast closes itself after
        /// a few seconds and without a trace the operator is left with "something happened, but
        /// what". The field is held by the SERVER, so a later-joining operator sees the same reason;
        /// a successful calibration clears it, so the row heals itself.</para>
        /// </summary>
        private void ApplyViolations(AdminPlayerView view, float alpha)
        {
            bool obstacle = view.obstacleCount > 0;
            bool outOfBounds = view.outOfBoundsCount > 0;
            bool error = !string.IsNullOrEmpty(view.calibrationError);

            SetChip(obstacleChip, obstacle,
                $"{AdminViolations.Label(AdminViolationKind.Obstacle)} {view.obstacleCount}",
                UiChipKind.Bad, alpha);
            SetChip(outOfBoundsChip, outOfBounds,
                $"{AdminViolations.Label(AdminViolationKind.OutOfBounds)} {view.outOfBoundsCount}",
                UiChipKind.Warn, alpha);
            SetChip(calibrationErrorChip, error, view.calibrationError, UiChipKind.Bad, alpha);

            SetCellActive(violationEmpty, !obstacle && !outOfBounds && !error);
            if (violationEmpty != null)
            {
                violationEmpty.color = Fade(Girdap.Muted, alpha);
            }

            LayoutViolationChips();
        }

        private static void SetChip(UiChip chip, bool visible, string text, UiChipKind kind,
            float alpha)
        {
            if (chip == null)
            {
                return;
            }

            SetCellActive(chip, visible);
            if (!visible)
            {
                return;
            }

            chip.Set(text, kind);
            if (chip.Label != null)
            {
                chip.Label.color = Fade(chip.Label.color, alpha);
            }
        }

        /// <summary>Flows the visible ledger chips left to right. ⚠️ Widths come from
        /// <see cref="UiChip.Set"/>, so the order has to be re-measured here rather than authored —
        /// no Layout Group in this kit.</summary>
        private void LayoutViolationChips()
        {
            float x = 0f;
            x = PlaceChip(obstacleChip, x);
            x = PlaceChip(outOfBoundsChip, x);
            PlaceChip(calibrationErrorChip, x);
        }

        private static float PlaceChip(UiChip chip, float x)
        {
            if (chip == null || !chip.gameObject.activeSelf || chip.Root == null)
            {
                return x;
            }

            RectTransform rect = chip.Root;
            rect.anchoredPosition = new Vector2(x, rect.anchoredPosition.y);
            return x + rect.sizeDelta.x + 4f; // CSS .viol gap
        }

        private static Color Fade(Color c, float alpha)
        {
            c.a *= alpha;
            return c;
        }

        private static Color Dim(Color c, float scale)
        {
            return new Color(c.r * scale, c.g * scale, c.b * scale, c.a);
        }

        // ---------------------------------------------------------------- internals

        /// <summary>
        /// Esc leaves edit mode.
        /// <para>⚠️ Read through <b>Input System</b>: the project is Input System-only and the old
        /// <c>Input.GetKeyDown</c> throws at runtime. No keyboard → skipped silently.</para>
        /// </summary>
        private void Update()
        {
            if (!_editing)
            {
                return;
            }

            Keyboard keyboard = Keyboard.current;
            if (keyboard != null && keyboard.escapeKey.wasPressedThisFrame)
            {
                CancelNameEdit();
            }
        }

        private static void SetInteractable(UiButtonStyle style, bool value)
        {
            if (style != null && style.Interactable != value)
            {
                style.SetInteractable(value);
            }
        }

        /// <summary>
        /// Opens name edit mode: the read-only name hides, the input field fills with the current
        /// name and takes focus. While open, roster refreshes leave the name alone (see
        /// <see cref="Bind"/>).
        /// </summary>
        private void BeginNameEdit()
        {
            AdminPlayerView view = AdminRoster.Instance != null
                ? AdminRoster.Instance.Find(_playerId)
                : null;
            if (view == null || view.HasLeft)
            {
                return;
            }

            SetNameEditActive(true);

            if (nameInput != null)
            {
                nameInput.text = view.name;
                nameInput.ActivateInputField();
            }
        }

        /// <summary>Sends the new name. Number <c>0</c> means "do NOT change the number" (§5.1):
        /// the server assigns shirt numbers and no UI overrides them.</summary>
        private void ApplyNameEdit()
        {
            if (!_editing)
            {
                return;
            }

            string typed = nameInput != null ? nameInput.text : "";
            SetNameEditActive(false);
            AdminCommands.SetIdentity(_playerId, typed, 0);
        }

        /// <summary>Cancels the edit — nothing is sent, the next <see cref="Bind"/> restores the
        /// name the server knows.</summary>
        private void CancelNameEdit()
        {
            SetNameEditActive(false);
        }

        private void SetNameEditActive(bool editing)
        {
            _editing = editing;

            if (nameEditRoot != null)
            {
                nameEditRoot.SetActive(editing);
            }

            if (nameText != null)
            {
                nameText.gameObject.SetActive(!editing);
            }

            if (idText != null)
            {
                // The inline editor takes the whole name cell; a leftover "#12" would sit on top of
                // the input field.
                idText.gameObject.SetActive(!editing);
            }
        }

        private void PressKick()
        {
            if (_kickArmedAt < 0f)
            {
                _kickArmedAt = Time.unscaledTime;
                RefreshKickButton();
                return;
            }

            _kickArmedAt = -1f;
            AdminCommands.Kick(_playerId);
            RefreshKickButton();
        }

        /// <summary>
        /// TAP: voids the player's current alignment and KEEPS the anchor saved on the headset
        /// (§5.2 <c>clear_calibration</c>, soft mode) — KALİBRE puts them back in one click. This
        /// is the everyday reset, so it fires on the first press: the press-duration grammar puts
        /// the friction on the destructive variant, not on this one.
        /// </summary>
        private void PressReset()
        {
            // A soft reset clears a standing "SİLİNDİ": the newer, weaker command is what happened.
            _purgedAt = -1f;
            AdminCommands.ClearCalibration(_playerId, keepSaved: true);
            RefreshResetButton();
        }

        /// <summary>
        /// HOLD (1 s): the same reset plus the anchor SAVED on that headset (hard mode) — the row's
        /// most destructive command, since it also destroys what KALİBRE would read and recovery
        /// becomes the manual A/B sequence in the headset.
        /// <para>The hold IS the confirmation; there is no two-step window on top of it
        /// (<see cref="HoldButton"/>).</para>
        /// </summary>
        private void PressPurge()
        {
            _purgedAt = Time.unscaledTime;
            AdminCommands.ClearCalibration(_playerId, keepSaved: false);
            RefreshResetButton();
        }

        /// <summary>
        /// Reloads calibration from the anchor SAVED on the headset (§5.3).
        /// <para>One step: it cannot take the player out of the fight, worst case nothing happens —
        /// the two-step lock is for irreversible commands like reset.</para>
        /// </summary>
        private void PressCalibrate()
        {
            if (_loadState == LoadState.Loading)
            {
                return; // double send: the button is already disabled, this is the second line
            }

            BeginCalibrationLoad();
            AdminCommands.ReloadCalibration(_playerId);
        }

        private void SetLoadState(LoadState state)
        {
            _loadState = state;
            _loadStateAt = Time.unscaledTime;
            RefreshCalibrateButton();
        }

        /// <summary>
        /// ÖLÇ is both COMMAND and INDICATOR (§10.8): "ÖLÇ" when unmeasured, the scale itself when
        /// measured. Disabled while uncalibrated — the server rejects it anyway.
        /// <para>⚠️ On failure (<c>scaleError</c> set) the label says so and the button stays
        /// ENABLED: re-measuring is exactly the job.</para>
        /// </summary>
        private void RefreshMeasureButton(AdminPlayerView view)
        {
            if (measureButton == null)
            {
                return;
            }

            bool usable = view.IsPlayer && view.calibrated && !view.HasLeft;
            bool failed = !string.IsNullOrEmpty(view.scaleError);
            bool measured = view.bodyScale > 0f;

            measureButton.SetLabel(failed ? LabelMeasureFailed
                : measured ? $"×{view.bodyScale:0.00}"
                : LabelMeasure);
            measureButton.SetKind(failed ? UiButtonKind.TextBad
                : measured ? UiButtonKind.TextGood
                : UiButtonKind.Normal);
            measureButton.SetInteractable(usable);
        }

        /// <summary>Two-step AT: idle is red lettering on the row's own surface, armed inverts to a
        /// solid confirm fill — the operator reads what the second press will do off the button
        /// itself. ⚠️ SIFIRLA does NOT go through here: its severity comes from press duration, so
        /// it paints a progress ramp instead (<see cref="RefreshResetButton"/>).</summary>
        private void RefreshKickButton()
        {
            if (kickButton == null)
            {
                return;
            }

            bool armed = _kickArmedAt >= 0f;
            kickButton.SetLabel(armed ? LabelConfirm : LabelKick);
            kickButton.SetKind(armed ? UiButtonKind.Confirm : UiButtonKind.TextBad);
        }

        /// <summary>SIFIRLA look. Idle is red lettering only (the tap is the everyday reset). The
        /// fill walks to red as the hold completes — that ramp IS the progress bar, so the operator
        /// sees how much of the wipe is left and can still slide off the button.</summary>
        private void RefreshResetButton()
        {
            if (resetButton == null)
            {
                return;
            }

            // ⚠️ The RESULT outranks the press: the wipe lands at the threshold, so from that
            // moment the button says SİLİNDİ even though the finger is still down.
            bool purged = _purgedAt >= 0f;
            bool holding = !purged && _resetHold != null && _resetHold.IsPressed;
            _resetHoldPainted = holding || purged;

            resetButton.SetLabel(holding ? LabelPurging : purged ? LabelPurged : LabelReset);
            // ⚠️ The wipe confirmation is GREEN even though the command was destructive: it reports
            // "the thing you asked for happened" — the same grammar as KALİBRE's TAMAM.
            resetButton.SetKind(purged ? UiButtonKind.TextGood : UiButtonKind.TextBad);
            resetButton.SetHold(holding ? Mathf.Max(0.02f, _resetHold.HoldProgress) : 0f);
        }

        /// <summary>
        /// While idle the KALİBRE button is an INDICATOR: calibrated = plain, over the floor drift
        /// threshold = accent lettering (§10.6 — alignment valid, headset space data stale),
        /// uncalibrated = a warning fill with "!". Disabled while loading; the result shows briefly,
        /// then idle.
        /// </summary>
        private void RefreshCalibrateButton()
        {
            if (calibrateButton == null)
            {
                return;
            }

            bool loading = _loadState == LoadState.Loading;
            calibrateButton.SetInteractable(!loading && !_hasLeft);

            switch (_loadState)
            {
                case LoadState.Loading:
                    calibrateButton.SetLabel(LabelCalibrateLoading);
                    calibrateButton.SetKind(UiButtonKind.On);
                    return;
                case LoadState.Ok:
                    calibrateButton.SetLabel(LabelCalibrateOk);
                    calibrateButton.SetKind(UiButtonKind.TextGood);
                    return;
                case LoadState.Failed:
                    calibrateButton.SetLabel(LabelCalibrateFailed);
                    calibrateButton.SetKind(UiButtonKind.TextBad);
                    return;
            }

            bool floorDrift = _calibrated &&
                              Mathf.Abs(_floorOffset) > ArenaProtocol.CALIB_FLOOR_WARN_METERS;

            calibrateButton.SetLabel(_calibrated ? LabelCalibrate : LabelCalibrateUncalibrated);
            // Uncalibrated shouts (filled), drift only tints: a drifting player can play, an
            // uncalibrated one cannot (same tone as AdminPlayerRow).
            calibrateButton.SetKind(!_calibrated ? UiButtonKind.WarnFill
                : floorDrift ? UiButtonKind.TextBlue
                : UiButtonKind.Normal);
        }

        /// <summary>⚠️ There is no "offline" state (§2) — a row is either expected back (with a
        /// countdown) or out of the game.</summary>
        private static string StateText(AdminPlayerView view)
        {
            if (view.IsReconnecting)
            {
                return $"yeniden bağlanıyor ({view.ReconnectSecondsLeft} sn)";
            }

            if (view.HasLeft)
            {
                return "ayrıldı";
            }

            if (!view.alive)
            {
                float remaining = view.RespawnRemaining;
                return remaining > 0.1f ? $"ölü ({Mathf.CeilToInt(remaining)} sn)" : "tabanda bekliyor";
            }

            return view.ready ? "hazır" : "bekliyor";
        }
    }
}
