using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using VortexArena.Core.Arena;

namespace VortexArena.Core.Editor
{
    /// <summary>Places the infrastructure an arena needs to join the network into the active scene;
    /// a new arena starts from an empty scene and is equipped with this tool.</summary>
    /// <remarks>
    /// ⚠️ Everything goes in as a PREFAB INSTANCE — never copied, never unpacked. With copies, one
    /// fix in the rig/calibration setup would mean manual work per arena.
    /// <para>⚠️ Idempotent: an existing instance of the same prefab is skipped, so a second run adds
    /// no second rig and no second boundary.</para>
    /// <para>⚠️ No <c>OVRComprehensiveInteractionRig</c> or Building Blocks rig is added on top: BB
    /// setup auto-unpacks the prefab, and both are already inside <c>VA_CameraRig</c>.</para>
    /// <para>⚠️ This tool does NOT place calibration anchors — they are cubes of the dimension mesh,
    /// generated by <c>Arena &gt; JSON'dan DimensionMesh Üret</c> at the points in the dimensions
    /// file's <c>calibration</c> field. Touching them from a second place would leave two sources
    /// with no clear winner.</para>
    /// <para>Manual work left (the report repeats it): generate the dimension mesh (anchors come
    /// with it) · move base zones to the real layout · build arena geometry around the WORLD ORIGIN
    /// (floor y=0) · set up environment art · bake NavMesh/lighting.</para>
    /// </remarks>
    public class TemplateBasicsLoader : EditorWindow
    {
        private const string PrefabRoot = "Assets/_Shared/App/Prefabs";
        private const string ArenaBoundaryPrefab = PrefabRoot + "/VA_ArenaBoundary.prefab";
        private const string CameraRigPrefab = PrefabRoot + "/VA_CameraRig.prefab";
        private const string PoseSyncPrefab = PrefabRoot + "/VA_PoseSync.prefab";
        private const string CalibrationPrefab = PrefabRoot + "/VA_CalibrationManager.prefab";
        private const string ModeHudPrefab = PrefabRoot + "/VA_ModeHud.prefab";
        private const string BaseZonePrefab = PrefabRoot + "/VA_BaseZone.prefab";

        private const string VenuesRoot = "Assets/Arenas/Venues";

        // Objects inside VA_CameraRig the boundary looks at. It can resolve only 'head' on its own
        // (Camera.main); the fade quad and warning text have NO fallback, so without wiring the
        // arena silently loses its warning.
        private const string HeadName = "CenterEyeAnchor";
        private const string FadeQuadName = "OutOfBoundsFade";
        private const string WarningTextName = "BoundaryWarningText";

        // Single source of truth for the base strip's look: the strip is never tinted at runtime, so
        // the material is written as an instance override while spawning (ApplyTeamMaterial).
        // Writing it into the prefab would not work — VA_BaseZone is ONE prefab and this override is
        // what separates red from blue.
        // ⚠️ The material's `_BaseColor` IS the team colour: BaseZoneVisibility reads it from the
        // strip's material to tint a dead player's x-ray ghost.
        private const string TeamRedMaterial = "Assets/_Shared/Materials/M_BaseZone_Red_Metallic_V2.mat";
        private const string TeamBlueMaterial = "Assets/_Shared/Materials/M_BaseZone_Blue_Metallic_V2.mat";

        [SerializeField] private bool includeModeHud = true;
        [SerializeField] private bool includeBaseZones = true;

        private Vector2 scroll;
        [System.NonSerialized] private List<string> lastReport;

        [MenuItem("Tools/VortexArena/Arena/Template Temellerini Yükle", false, 1)]
        private static void Open()
        {
            var window = GetWindow<TemplateBasicsLoader>(true, "Template Temelleri", true);
            window.minSize = new Vector2(440f, 300f);
            window.Show();
        }

        private void OnGUI()
        {
            scroll = EditorGUILayout.BeginScrollView(scroll);

            EditorGUILayout.LabelField("Aktif sahne: " + SceneManager.GetActiveScene().name, EditorStyles.boldLabel);
            EditorGUILayout.Space();

            EditorGUILayout.LabelField("Her zaman konur", EditorStyles.miniBoldLabel);
            EditorGUILayout.LabelField("VA_ArenaBoundary · VA_CameraRig · VA_PoseSync · VA_CalibrationManager",
                EditorStyles.wordWrappedMiniLabel);

            EditorGUILayout.Space();
            EditorGUILayout.LabelField("Seçime bağlı", EditorStyles.miniBoldLabel);
            includeModeHud = EditorGUILayout.ToggleLeft(
                new GUIContent("VA_ModeHud", "Lobi sahnesinde İSTENMEZ — lobide mod HUD'ı yoktur."),
                includeModeHud);
            includeBaseZones = EditorGUILayout.ToggleLeft(
                new GUIContent("Taban bölgeleri (Base_Red / Base_Blue)",
                    "Lobi sahnesinde İSTENMEZ — lobide canlanma bölgesi yoktur."),
                includeBaseZones);

            EditorGUILayout.Space();
            EditorGUILayout.HelpBox(
                "Hepsi prefab ÖRNEĞİ olarak konur ve var olanlar atlanır (idempotent). " +
                "Boyut dosyası mekan klasöründen çözülüp ArenaBoundary'ye bağlanır.\n\n" +
                "Kalibrasyon işaretçileri BURADAN gelmez: 'Arena > JSON'dan DimensionMesh Üret' " +
                "ile üretilen ölçü maketinin anchor_a/anchor_b küpleridir.",
                MessageType.Info);

            EditorGUILayout.Space();
            if (GUILayout.Button("Yükle", GUILayout.Height(28f)))
            {
                lastReport = Load(includeModeHud, includeBaseZones);
                for (int i = 0; i < lastReport.Count; i++)
                {
                    Debug.Log("[TemplateBasics] " + lastReport[i]);
                }
            }

            if (lastReport != null)
            {
                EditorGUILayout.Space();
                EditorGUILayout.LabelField("Son çalıştırma", EditorStyles.boldLabel);
                for (int i = 0; i < lastReport.Count; i++)
                {
                    EditorGUILayout.LabelField("• " + lastReport[i], EditorStyles.wordWrappedLabel);
                }
            }

            EditorGUILayout.EndScrollView();
        }

        // ----------------------------------------------------------------- load

        /// <summary>Places the basics into the active scene and returns what was done, line by
        /// line. Throws NO exception.</summary>
        public static List<string> Load(bool modeHud, bool baseZones)
        {
            var report = new List<string>();
            Scene scene = SceneManager.GetActiveScene();

            if (!scene.IsValid())
            {
                report.Add("HATA: geçerli bir aktif sahne yok.");
                return report;
            }

            int undoGroup = Undo.GetCurrentGroup();
            Undo.SetCurrentGroupName("VortexArena Template Temelleri");

            EnsurePrefab(ArenaBoundaryPrefab, report);
            GameObject cameraRig = EnsurePrefab(CameraRigPrefab, report);
            EnsurePrefab(PoseSyncPrefab, report);
            GameObject calibration = EnsurePrefab(CalibrationPrefab, report);

            if (modeHud)
            {
                EnsurePrefab(ModeHudPrefab, report);
            }

            if (baseZones)
            {
                EnsureBaseZones(report);
            }

            WireCalibration(calibration, cameraRig, report);
            WireBoundaryToRig(cameraRig, report);
            BindDimensions(scene, report);
            ReportCalibrationMarkers(report);

            Undo.CollapseUndoOperations(undoGroup);
            EditorSceneManager.MarkSceneDirty(scene);

            report.Add("ELDE: ölçü maketini üret (kalibrasyon işaretçileri ondan gelir) · " +
                       "taban bölgelerini gerçek yerleşime göre taşı · " +
                       "arena geometrisini DÜNYA ORİJİNİNE göre kur (zemin y=0; arena uzayı = " +
                       "dünya uzayı, sahneyi kaydırmak herkesin ağ konumunu kaydırır) · " +
                       "environment sanatını kur · NavMesh/ışık bake et.");
            report.Add("Sonra 'Tools > VortexArena > Build > Configure All Build Elements' çalıştır.");
            return report;
        }

        /// <summary>Instantiates the prefab unless the scene already has an instance; returns the
        /// existing one (callers wire against it) and reports a missing prefab.</summary>
        private static GameObject EnsurePrefab(string prefabPath, List<string> report)
        {
            var asset = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);
            if (asset == null)
            {
                report.Add($"HATA: prefab bulunamadı — '{prefabPath}'. Konmadı.");
                return null;
            }

            GameObject existing = FindInstanceOf(asset);
            if (existing != null)
            {
                report.Add($"atlandı (zaten var): {asset.name}");
                return existing;
            }

            var instance = (GameObject)PrefabUtility.InstantiatePrefab(asset);
            Undo.RegisterCreatedObjectUndo(instance, "Template Temeli");
            report.Add($"kondu: {asset.name}");
            return instance;
        }

        /// <summary>Finds a scene instance of the given prefab asset.</summary>
        /// <remarks>Matched by asset path: matching by component type would count any other object
        /// carrying that component as "already there".</remarks>
        private static GameObject FindInstanceOf(GameObject prefabAsset)
        {
            string assetPath = AssetDatabase.GetAssetPath(prefabAsset);
            GameObject[] roots = SceneManager.GetActiveScene().GetRootGameObjects();

            for (int i = 0; i < roots.Length; i++)
            {
                Transform[] all = roots[i].GetComponentsInChildren<Transform>(true);
                for (int k = 0; k < all.Length; k++)
                {
                    GameObject candidate = all[k].gameObject;
                    if (!PrefabUtility.IsAnyPrefabInstanceRoot(candidate))
                    {
                        continue;
                    }

                    GameObject source = PrefabUtility.GetCorrespondingObjectFromOriginalSource(candidate);
                    if (source != null && AssetDatabase.GetAssetPath(source) == assetPath)
                    {
                        return candidate;
                    }
                }
            }

            return null;
        }

        /// <summary>Places two base zones (<c>Base_Red</c> / <c>Base_Blue</c>) and stamps their
        /// teams. Skipped entirely when the scene already has a <see cref="BaseZone"/> — they may
        /// have been positioned by hand.</summary>
        private static void EnsureBaseZones(List<string> report)
        {
            BaseZone[] existing =
                Object.FindObjectsByType<BaseZone>(FindObjectsInactive.Include, FindObjectsSortMode.None);
            if (existing.Length > 0)
            {
                report.Add($"atlandı (zaten var): taban bölgesi ×{existing.Length}");
                return;
            }

            var asset = AssetDatabase.LoadAssetAtPath<GameObject>(BaseZonePrefab);
            if (asset == null)
            {
                report.Add($"HATA: prefab bulunamadı — '{BaseZonePrefab}'. Taban bölgeleri konmadı.");
                return;
            }

            SpawnBaseZone(asset, "Base_Red", Team.Red, TeamRedMaterial);
            SpawnBaseZone(asset, "Base_Blue", Team.Blue, TeamBlueMaterial);
            report.Add("kondu: Base_Red + Base_Blue (yerleri ELLE ayarlanır)");
        }

        /// <summary>Spawns a team coloured zone from the single <c>VA_BaseZone</c> prefab.</summary>
        /// <remarks>⚠️ The strip is never tinted at runtime, so the price of not keeping one prefab
        /// per team is writing the material here; separate prefabs would turn one strip geometry fix
        /// into manual work in two files.</remarks>
        private static void SpawnBaseZone(GameObject asset, string name, Team team, string materialPath)
        {
            var instance = (GameObject)PrefabUtility.InstantiatePrefab(asset);
            instance.name = name;
            Undo.RegisterCreatedObjectUndo(instance, "Taban Bölgesi");

            ApplyTeamMaterial(instance, materialPath);

            var zone = instance.GetComponent<BaseZone>();
            if (zone == null)
            {
                return;
            }

            var serialized = new SerializedObject(zone);
            SerializedProperty teamProp = serialized.FindProperty("team");
            if (teamProp != null)
            {
                teamProp.enumValueIndex = (int)team;
                serialized.ApplyModifiedPropertiesWithoutUndo();
                EditorUtility.SetDirty(zone);
            }
        }

        /// <summary>Paints the zone's strips with the team material (prefab override).</summary>
        private static void ApplyTeamMaterial(GameObject instance, string materialPath)
        {
            var material = AssetDatabase.LoadAssetAtPath<Material>(materialPath);
            if (material == null)
            {
                return;
            }

            Renderer[] renderers = instance.GetComponentsInChildren<Renderer>(true);
            for (int i = 0; i < renderers.Length; i++)
            {
                renderers[i].sharedMaterial = material;
                EditorUtility.SetDirty(renderers[i]);
            }
        }

        /// <summary>Wires <see cref="ArenaCalibrator"/>'s scene-facing field; it stays empty in the
        /// prefab asset (normal) and can only be filled on a scene instance.</summary>
        /// <remarks>⚠️ <c>anchorA</c>/<c>anchorB</c> are NOT wired: the calibrator resolves the
        /// anchors at runtime from the mesh's <see cref="DimensionAnchor"/> cubes (or by name).
        /// Wiring them here would leave a copy that dies when the mesh is regenerated.</remarks>
        private static void WireCalibration(
            GameObject calibration,
            GameObject cameraRig,
            List<string> report)
        {
            if (calibration == null)
            {
                return;
            }

            var calibrator = calibration.GetComponentInChildren<ArenaCalibrator>(true);
            if (calibrator == null)
            {
                report.Add("UYARI: VA_CalibrationManager altında ArenaCalibrator yok — alanlar bağlanamadı.");
                return;
            }

            var serialized = new SerializedObject(calibrator);
            if (AssignObject(serialized, "rigRoot", cameraRig != null ? cameraRig.transform : null))
            {
                serialized.ApplyModifiedPropertiesWithoutUndo();
                EditorUtility.SetDirty(calibrator);
                report.Add("bağlandı: ArenaCalibrator.rigRoot → VA_CameraRig");
            }
        }

        /// <summary>Wires <see cref="ArenaBoundary"/>'s rig-facing fields: HMD, fade quad and
        /// out-of-bounds warning text, all inside <c>VA_CameraRig</c>.</summary>
        /// <remarks>⚠️ Skipping this silently disables the boundary: <c>head</c> falls back to
        /// <c>Camera.main</c>, but the fade and the warning have no fallback — the line is crossed
        /// and nothing happens. An empty field produces no visible error, hence the wiring in
        /// code.</remarks>
        private static void WireBoundaryToRig(GameObject cameraRig, List<string> report)
        {
            var boundary = Object.FindFirstObjectByType<ArenaBoundary>(FindObjectsInactive.Include);
            if (boundary == null || cameraRig == null)
            {
                return;
            }

            Transform head = FindDescendant(cameraRig.transform, HeadName);
            Transform fade = FindDescendant(cameraRig.transform, FadeQuadName);
            Transform warning = FindDescendant(cameraRig.transform, WarningTextName);

            var serialized = new SerializedObject(boundary);
            bool wired = false;

            wired |= AssignObject(serialized, "head", head);
            wired |= AssignObject(serialized, "fadeRenderer",
                fade != null ? fade.GetComponent<Renderer>() : null);
            wired |= AssignObject(serialized, "warningText",
                warning != null ? warning.GetComponent<TextMesh>() : null);

            if (wired)
            {
                serialized.ApplyModifiedPropertiesWithoutUndo();
                EditorUtility.SetDirty(boundary);
                report.Add("bağlandı: ArenaBoundary head/fadeRenderer/warningText → VA_CameraRig");
            }

            if (fade == null || warning == null)
            {
                report.Add($"UYARI: rig altında '{FadeQuadName}'/'{WarningTextName}' yok — " +
                           "muhafaza sınır aşımında hiçbir şey göstermez.");
            }
        }

        /// <summary>Only CHECKS for calibration anchors, never places them — they come with the
        /// dimension mesh, generated solely by <c>JSON'dan DimensionMesh Üret</c>.</summary>
        /// <remarks>Never passed over silently: an arena without anchors cannot be aligned on site,
        /// and the gap is only noticed once someone is in the venue with a headset.</remarks>
        private static void ReportCalibrationMarkers(List<string> report)
        {
            DimensionAnchor[] anchors =
                Object.FindObjectsByType<DimensionAnchor>(FindObjectsInactive.Include, FindObjectsSortMode.None);
            if (anchors.Length >= 2)
            {
                report.Add($"bulundu: kalibrasyon işaretçisi ×{anchors.Length} (ölçü maketinden).");
                return;
            }

            report.Add("UYARI: sahnede kalibrasyon işaretçisi yok — 'Tools > VortexArena > Arena > " +
                       "JSON'dan DimensionMesh Üret' çalıştır. İşaretçiler maketin anchor_a/anchor_b " +
                       "küpleridir ve yerleri boyut dosyasının 'calibration' alanından gelir; " +
                       "onlarsız hizalama YAPILAMAZ.");
        }

        /// <summary>Writes the field only with a non-null value and only when empty (hand wired
        /// references are kept).</summary>
        private static bool AssignObject(SerializedObject serialized, string field, Object value)
        {
            if (value == null)
            {
                return false;
            }

            SerializedProperty property = serialized.FindProperty(field);
            if (property == null || property.objectReferenceValue != null)
            {
                return false;
            }

            property.objectReferenceValue = value;
            return true;
        }

        /// <summary>Resolves the dimensions file from the scene's venue folder and binds it to
        /// <see cref="ArenaBoundary"/>.</summary>
        /// <remarks>The file is per VENUE:
        /// <c>Venues/&lt;Venue&gt;/Data/&lt;Venue&gt;_dimensions.json</c>. Missing file only warns —
        /// a boundary without dimensions disables itself.</remarks>
        private static void BindDimensions(Scene scene, List<string> report)
        {
            var boundary = Object.FindFirstObjectByType<ArenaBoundary>(FindObjectsInactive.Include);
            if (boundary == null)
            {
                report.Add("UYARI: sahnede ArenaBoundary yok — boyut dosyası bağlanamadı.");
                return;
            }

            var serialized = new SerializedObject(boundary);
            SerializedProperty property = serialized.FindProperty("dimensionsJson");
            if (property == null)
            {
                report.Add("UYARI: ArenaBoundary'de 'dimensionsJson' alanı bulunamadı.");
                return;
            }

            if (property.objectReferenceValue != null)
            {
                report.Add("atlandı (zaten bağlı): ArenaBoundary.dimensionsJson");
                return;
            }

            string venue = ResolveVenueFromScenePath(scene.path);
            if (string.IsNullOrEmpty(venue))
            {
                report.Add("UYARI: sahne bir mekan klasöründe değil — boyut dosyasını ELLE bağla " +
                           "(sahne henüz kaydedilmediyse önce kaydet).");
                return;
            }

            string jsonPath = $"{VenuesRoot}/{venue}/Data/{venue}_dimensions.json";
            var json = AssetDatabase.LoadAssetAtPath<TextAsset>(jsonPath);
            if (json == null)
            {
                report.Add($"UYARI: boyut dosyası yok — '{jsonPath}'. Muhafaza ÖLÇÜSÜZ, arena sınırsız.");
                return;
            }

            property.objectReferenceValue = json;
            serialized.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(boundary);
            report.Add($"bağlandı: ArenaBoundary.dimensionsJson → {jsonPath}");
        }

        /// <summary>Extracts the venue name from
        /// <c>Assets/Arenas/Venues/&lt;Venue&gt;/…</c>; empty when the scene is outside a venue
        /// folder.</summary>
        public static string ResolveVenueFromScenePath(string scenePath)
        {
            if (string.IsNullOrEmpty(scenePath))
            {
                return string.Empty;
            }

            string normalized = scenePath.Replace('\\', '/');
            if (!normalized.StartsWith(VenuesRoot + "/", System.StringComparison.OrdinalIgnoreCase))
            {
                return string.Empty;
            }

            string tail = normalized.Substring(VenuesRoot.Length + 1);
            int slash = tail.IndexOf('/');
            return slash > 0 ? tail.Substring(0, slash) : string.Empty;
        }

        private static Transform FindDescendant(Transform root, string name)
        {
            Transform[] all = root.GetComponentsInChildren<Transform>(true);
            for (int i = 0; i < all.Length; i++)
            {
                if (all[i] != root && string.Equals(all[i].name, name, System.StringComparison.Ordinal))
                {
                    return all[i];
                }
            }

            return null;
        }
    }
}
